const toolboxeaipLink       = "http://ais.skyguide.corp/map/eaipbytable.html";
const cocesnaLink           = "https://cocesna.org/home/aim/"
const dutchCaribbeanLink    = "http://dc-ansp.org/eAIS/eaip-dutch-caribbean/"
const pacificLink           = "https://shop.aeropath.aero/collections/pacific-aip"
const asecnaLink            = "https://aim.asecna.aero/html/index-fr-FR.html";
const aipDenmarkLink        = "https://aim.naviair.dk/en/";
const aipFranceLink         = "https://www.sia.aviation-civile.gouv.fr/";
const aipBelgiumLink        = "https://ops.skeyes.be/html/belgocontrol_static/eaip/eAIP_Product/index.html";
const aipRussiaLink         = "http://www.caiga.ru/common/?lang=en";
const aipAustraliaLink      = "https://www.airservicesaustralia.com/aip/aip.asp";
const aipUSALink            = "https://www.faa.gov/air_traffic/publications/atpubs/aip_html/"
const aipSwitzerlandLink    = "http://eaip.skyguide.corp/"
const aipUKLink             = "https://nats-uk.ead-it.com/cms-nats/opencms/en/Publications/AIP/"
const aipItalyLink          = "https://www.enav.it/en/login-required"
const aipSerbiaMontenegro   = "https://smatsa.rs/en/aeronautical-information-publication-aip/"

const aipTileData = [{
		id: "oa",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/1024px-Flag_of_the_Taliban.svg.png",
		icao: "OA",
		country: "Afghanistan",
		link: "http://acaa.gov.af/aip-aeronautical-information-publication/",
		aip: "green"
	}, {
		id: "da",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/900px-Flag_of_Algeria.svg.png",
		icao: "DA",
		country: "Algeria",
		link: "https://www.sia-enna.dz/",
		aip: "green"
	}, {
		id: "la",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/900px-Flag_of_Albania.svg.png",
		icao: "LA",
		country: "Albania",
		link: "https://albcontrol.al/al/aip/",
		aip: "green"
	}, {
		id: "fn",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/900px-Flag_of_Angola.svg.png",
		icao: "FN",
		country: "Angola",
		link: "http://www.inavic.gv.ao/opencms/inavicsite/sia/",
		aip: "green"
	}, {
		id: "sa",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/1000px-Flag_of_Argentina.svg.png",
		icao: "SA",
		country: "Argentina",
		link: "http://ais.anac.gov.ar/aip",
		aip: "green"
	}, {
		id: "ud",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/1000px-Flag_of_Armenia.svg.png",
		icao: "UD",
		country: "Armenia",
		link: "http://www.armats.am/activities/ais/eaip",
		aip: "green"
	}, {
		id: "fh-ascension",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Ascension_Island.svg/1000px-Flag_of_Ascension_Island.svg.png",
		icao: "FH",
		country: "Ascension Island",
		link: "",
		aip: "black"
	}, {
		id: "yb",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/1000px-Flag_of_Australia.svg.png",
		icao: "YB",
		country: "Australia",
		link: aipAustraliaLink,
		aip: "green"
	}, {
		id: "lo",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/1000px-Flag_of_Austria.svg.png",
		icao: "LO",
		country: "Austria",
		link: "https://eaip.austrocontrol.at/",
		aip: "green"
	}, {
		id: "ub",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1000px-Flag_of_Azerbaijan.svg.png",
		icao: "UB",
		country: "Azerbaijan",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "ob",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/1000px-Flag_of_Bahrain.svg.png",
		icao: "OB",
		country: "Bahrain",
		link: "http://www.bahrainaims.com/aip_button.html",
		aip: "green"
	}, {
		id: "vg",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/1000px-Flag_of_Bangladesh.svg.png",
		icao: "VG",
		country: "Bangladesh",
		link: "http://www.caab.gov.bd/aip/index.html",
		aip: "green"
	}, {
		id: "tb",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/1000px-Flag_of_Barbados.svg.png",
		icao: "TB",
		country: "Barbados",
		link: "http://bcad.gov.bb/eAIP/bcad/index.php",
		aip: "green"
	}, {
		id: "eb-belgium",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/1000px-Flag_of_Belgium.svg.png",
		icao: "EB",
		country: "Belgium",
		link: aipBelgiumLink,
		aip: "green"
	}, {
		id: "um",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/1000px-Flag_of_Belarus.svg.png",
		icao: "UM",
		country: "Belarus",
		link: "http://www.ban.by/en/aeronautical-information-aip",
		aip: "green"
	}, {
		id: "db",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/1000px-Flag_of_Benin.svg.png",
		icao: "DB",
		country: "Benin",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "tx",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bermuda.svg/1000px-Flag_of_Bermuda.svg.png",
		icao: "TX",
		country: "Bermuda",
		link: "https://www.airportauthority.bm/ais/aeronautical-info-publication.html",
		aip: "green"
	}, {
		id: "vq",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/1000px-Flag_of_Bhutan.svg.png",
		icao: "VQ",
		country: "Bhutan",
		link: "https://www.doat.gov.bt/aip/",
		aip: "green"
	}, {
		id: "lq",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/1000px-Flag_of_Bosnia_and_Herzegovina.svg.png",
		icao: "LQ",
		country: "Bosnia & Herzegowina",
		link: "https://eaip.bhansa.gov.ba/",
		aip: "green"
	}, {
		id: "sl",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bandera_de_Bolivia_%28Estado%29.svg/1000px-Bandera_de_Bolivia_%28Estado%29.svg.png",
		icao: "SL",
		country: "Bolivia",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "fb",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/1000px-Flag_of_Botswana.svg.png",
		icao: "FB",
		country: "Botswana",
		link: "",
		aip: "red"
	}, {
		id: "fj",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_the_Commissioner_of_the_British_Indian_Ocean_Territory.svg/1000px-Flag_of_the_Commissioner_of_the_British_Indian_Ocean_Territory.svg.png",
		icao: "FJ",
		country: "British Indian Ocean Territory",
		link: "https://www.aidu.mod.uk/aip/aipVolumes.html#",
		aip: "green"
	}, {
		id: "lb",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/1000px-Flag_of_Bulgaria.svg.png",
		icao: "LB",
		country: "Bulgaria",
		link: "https://www.bulatsa.com/wp-content/themes/bulatsa-theme/AIP/Start.htm",
		aip: "green"
	}, {
		id: "df",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/1000px-Flag_of_Burkina_Faso.svg.png",
		icao: "DF",
		country: "Burkina Faso",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "sb",
		img: "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/1024px-Flag_of_Brazil.svg.png",
		icao: "SB",
		country: "Brazil",
		link: "https://aisweb.decea.mil.br/",
		aip: "green"
	}, {
		id: "vd",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/1000px-Flag_of_Cambodia.svg.png",
		icao: "VD",
		country: "Cambodia",
		link: "http://www.civilaviation.gov.kh/en",
		aip: "green"
	}, {
		id: "fk",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/1000px-Flag_of_Cameroon.svg.png",
		icao: "FK",
		country: "Cameroon",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "cy",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Canada.svg/1000px-Flag_of_Canada.svg.png",
		icao: "CY",
		country: "Canada",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "mw",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_the_Cayman_Islands.svg/1000px-Flag_of_the_Cayman_Islands.svg.png",
		icao: "MW",
		country: "Cayman Islands",
		link: "https://www.caymanairports.com/aeronautical-information-publication/",
		aip: "green"
	}, {
		id: "fe",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Central_African_Republic.svg/1000px-Flag_of_the_Central_African_Republic.svg.png",
		icao: "FE",
		country: "Central African Republic",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "sc",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/1000px-Flag_of_Chile.svg.png",
		icao: "SC",
		country: "Chile",
		link: "https://aipchile.dgac.gob.cl/",
		aip: "green"
	}, {
		id: "zb",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/1000px-Flag_of_the_People%27s_Republic_of_China.svg.png",
		icao: "ZB",
		country: "China",
		link: "https://www.eaipchina.cn/",
		aip: "green"
	}, {
		id: "sk",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/1000px-Flag_of_Colombia.svg.png",
		icao: "SK",
		country: "Colombia",
		link: "https://www.aerocivil.gov.co/servicios-a-la-navegacion/servicio-de-informacion-aeronautica-ais/aip",
		aip: "green"
	}, {
		id: "fm-comoros",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/1000px-Flag_of_the_Comoros.svg.png",
		icao: "FM",
		country: "Comoros",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "fc",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Republic_of_the_Congo.svg/1000px-Flag_of_the_Republic_of_the_Congo.svg.png",
		icao: "FC",
		country: "Congo",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "nc",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Flag_of_the_Cook_Islands.svg/1000px-Flag_of_the_Cook_Islands.svg.png",
		icao: "NC",
		country: "Cook Islands",
		link: pacificLink,
		aip: "green"
	}, {
		id: "ld",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Flag_of_Croatia_at_the_UN.svg/1000px-Flag_of_Croatia_at_the_UN.svg.png",
		icao: "LD",
		country: "Croatia",
		link: "https://www.crocontrol.hr/UserDocsImages/AIS%20produkti/eAIP/start.html",
		aip: "green"
	}, {
		id: "mu",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/1000px-Flag_of_Cuba.svg.png",
		icao: "MU",
		country: "Cuba",
		link: "https://aismet.avianet.cu/html/aip.html",
		aip: "green"
	}, {
		id: "lc-cyprus",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/1000px-Flag_of_Cyprus.svg.png",
		icao: "LC",
		country: "Cyprus",
		link: "http://www.mcw.gov.cy/mcw/DCA/AIS/ais.nsf/index_en/index_en",
		aip: "green"
	}, {
		id: "lc-akrotiri",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/RAF_Akrotiri_flag.svg/1024px-RAF_Akrotiri_flag.svg.png",
		icao: "LC",
		country: "Akrotiri",
		link: "https://www.aidu.mod.uk/aip/aipVolumes.html#ad-tab",
		aip: "green"
	}, {
		id: "lc-dhekelia",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Flag_of_the_Dhekelia_Garrison.svg/1024px-Flag_of_the_Dhekelia_Garrison.svg.png",
		icao: "LC",
		country: "Dhekelia",
		link: "https://www.aidu.mod.uk/aip/aipVolumes.html#ad-tab",
		aip: "green"
	}, {
		id: "lk",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/1000px-Flag_of_the_Czech_Republic.svg.png",
		icao: "LK",
		country: "Czech Rebulic",
		link: "https://aim.rlp.cz/",
		aip: "green"
	}, {
		id: "fz",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/1024px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png",
		icao: "FZ",
		country: "Democratic Republic of Congo",
		link: "",
		aip: "red"
	}, {
		id: "ek",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/1000px-Flag_of_Denmark.svg.png",
		icao: "EK",
		country: "Denmark",
		link: aipDenmarkLink,
		aip: "green"
	}, {
		id: "md",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/1000px-Flag_of_the_Dominican_Republic.svg.png",
		icao: "MD",
		country: "Dominican Republic",
		link: "https://aip.idac.gob.do/Aip/IndexAip",
		aip: "green"
	}, {
		id: "se",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/1000px-Flag_of_Ecuador.svg.png",
		icao: "SE",
		country: "Ecuador",
		link: "http://www.ais.aviacioncivil.gob.ec/ifis3/aip/AIP",
		aip: "green"
	}, {
		id: "fg",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Equatorial_Guinea.svg/1000px-Flag_of_Equatorial_Guinea.svg.png",
		icao: "FG",
		country: "Equatorial Guinea",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "ee",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Estonia.png/1024px-Flag_of_Estonia.png",
		icao: "EE",
		country: "Estonia",
		link: "https://aim.eans.ee/en/eaip",
		aip: "green"
	}, {
		id: "fd",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Eswatini.svg/1000px-Flag_of_Eswatini.svg.png",
		icao: "FD",
		country: "eSwatini",
		link: "",
		aip: "red"
	}, {
		id: "he",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/1000px-Flag_of_Egypt.svg.png",
		icao: "HE",
		country: "Egypt",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "ek-faroer",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Flag_of_the_Faroe_Islands.svg/1000px-Flag_of_the_Faroe_Islands.svg.png",
		icao: "EK",
		country: "Faroe Islands",
		link: aipDenmarkLink,
		aip: "green"
	}, {
		id: "ef",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/1000px-Flag_of_Finland.svg.png",
		icao: "EF",
		country: "Finland",
		link: "https://www.ais.fi/en",
		aip: "green"
	}, {
		id: "lf-france",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Flag_of_France.png/1024px-Flag_of_France.png",
		icao: "LF",
		country: "France",
		link: aipFranceLink,
		aip: "green"
	}, {
		id: "lf-saintPierre",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_Saint-Pierre_and_Miquelon.svg/1024px-Flag_of_Saint-Pierre_and_Miquelon.svg.png",
		icao: "LF",
		country: "Saint Pierre and Miquelon",
		link: aipFranceLink,
		aip: "green"
	}, {
		id: "lf-andorra",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Andorra.svg/1024px-Flag_of_Andorra.svg.png",
		icao: "LF",
		country: "Andorra",
		link: aipFranceLink,
		aip: "green"
	}, {
		id: "fo",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Gabon.svg/1000px-Flag_of_Gabon.svg.png",
		icao: "FO",
		country: "Gabon",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "gb",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_The_Gambia.svg/1000px-Flag_of_The_Gambia.svg.png",
		icao: "GB",
		country: "Gambia",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "ug",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/1000px-Flag_of_Georgia.svg.png",
		icao: "UG",
		country: "Georgia",
		link: "https://airnav.ge/eaip/history-en-GB.html",
		aip: "green"
	}, {
		id: "ed",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/1000px-Flag_of_Germany.svg.png",
		icao: "ED",
		country: "Germany",
		link: "https://www.eisenschmidt.aero/account/downloads",
		aip: "green"
	}, {
		id: "et",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Coat_of_arms_of_Germany.svg/1000px-Coat_of_arms_of_Germany.svg.png",
		icao: "ET",
		country: "Germany Military Airports",
		link: "https://www.milais.org/publications.php?ZnJtaWQ9MA==",
		aip: "green"
	}, {
		id: "dg",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/1000px-Flag_of_Ghana.svg.png",
		icao: "DG",
		country: "Ghana",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "lg",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Greece.png/1024px-Flag_of_Greece.png",
		icao: "LG",
		country: "Greece",
		link: "http://www.ypa.gr/aip/publications/",
		aip: "green"
	}, {
		id: "bg",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_Greenland.png/1024px-Flag_of_Greenland.png",
		icao: "BG",
		country: "Greenland",
		link: aipDenmarkLink,
		aip: "green"
	}, {
		id: "mt",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Haiti.svg/1000px-Flag_of_Haiti.svg.png",
		icao: "MT",
		country: "Haiti",
		link: "https://ofnac.gouv.ht/services/#tab-606ef7842d3d3180b26",
		aip: "green"
	}, {
		id: "mh",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Flag_of_Honduras.svg/1000px-Flag_of_Honduras.svg.png",
		icao: "MH",
		country: "Honduras",
		link: "https://ahac.gob.hn/",
		aip: "green"
	}, {
		id: "vh",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Hong_Kong.svg/900px-Flag_of_Hong_Kong.svg.png",
		icao: "VH",
		country: "Hong Kong",
		link: "https://www.ais.gov.hk/",
		aip: "green"
	}, {
		id: "lh",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/1000px-Flag_of_Hungary.svg.png",
		icao: "LH",
		country: "Hungary",
		link: "https://ais-en.hungarocontrol.hu/aip/",
		aip: "green"
	}, {
		id: "bi",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/1000px-Flag_of_Iceland.svg.png",
		icao: "BI",
		country: "Iceland",
		link: "https://eaip.isavia.is/",
		aip: "green"
	}, {
		id: "fm-eparses",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Flag_of_the_French_Southern_and_Antarctic_Lands.svg/1000px-Flag_of_the_French_Southern_and_Antarctic_Lands.svg.png",
		icao: "FM",
		country: "Illes Eparses",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "vi",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_India.png/1024px-Flag_of_India.png",
		icao: "VI",
		country: "India",
		link: "https://aim-india.aai.aero/",
		aip: "green"
	}, {
		id: "wi",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/1000px-Flag_of_Indonesia.svg.png",
		icao: "WI",
		country: "Indonesia",
		link: "https://aimindonesia.dephub.go.id/signin.php",
		aip: "green"
	}, {
		id: "oi",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/1000px-Flag_of_Iran.svg.png",
		icao: "OI",
		country: "Iran",
		link: "https://ais.airport.ir/homehttps://ais.airport.ir/home",
		aip: "green"
	}, {
		id: "or",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/1000px-Flag_of_Iraq.svg.png",
		icao: "OR",
		country: "Iraq",
		link: "https://icaa.gov.iq/home/ais-publication/",
		aip: "green"
	}, {
		id: "ei",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/1000px-Flag_of_Ireland.svg.png",
		icao: "EI",
		country: "Ireland",
		link: "https://www.iaa.ie/commercial-aviation/aeronautical-information-management-1",
		aip: "green"
	}, {
		id: "ll",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/1000px-Flag_of_Israel.svg.png",
		icao: "LL",
		country: "Israel",
		link: "https://www.gov.il/en/departments/guides/aip-israel?chapterIndex=1",
		aip: "green"
	}, {
		id: "li-italy",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/1000px-Flag_of_Italy.svg.png",
		icao: "LI",
		country: "Italy",
		link: aipItalyLink,
		aip: "green"
	}, {
		id: "li-vatican",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_the_Vatican_City_%282001%E2%80%932023%29.svg/1024px-Flag_of_the_Vatican_City_%282001%E2%80%932023%29.svg.png",
		icao: "LI",
		country: "Vatican City",
		link: aipItalyLink,
		aip: "green"
	}, {
		id: "li-sanMarino",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_San_Marino.svg/1024px-Flag_of_San_Marino.svg.png",
		icao: "LI",
		country: "San Marino",
		link: aipItalyLink,
		aip: "green"
	}, {
		id: "di",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg/1000px-Flag_of_C%C3%B4te_d%27Ivoire.svg.png",
		icao: "DI",
		country: "Ivory Coast",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "rj",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/1000px-Flag_of_Japan.svg.png",
		icao: "RJ",
		country: "Japan",
		link: "https://aisjapan.mlit.go.jp/Login.do",
		aip: "green"
	}, {
		id: "oj",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Jordan.png/1024px-Flag_of_Jordan.png",
		icao: "OJ",
		country: "Jordan",
		link: "http://www.carc.gov.jo/en/ais",
		aip: "green"
	}, {
		id: "ua",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/1000px-Flag_of_Kazakhstan.svg.png",
		icao: "UA",
		country: "Kazakhstan",
		link: "https://www.ans.kz/en/ais/eaip",
		aip: "green"
	}, {
		id: "hk",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/1000px-Flag_of_Kenya.svg.png",
		icao: "HK",
		country: "Kenia",
		link: "https://eaip.kcaa.or.ke/eAIPHome.aspx",
		aip: "green"
	}, {
		id: "rk",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/1000px-Flag_of_South_Korea.svg.png",
		icao: "RK",
		country: "South Korea",
		link: "http://ais.casa.go.kr/",
		aip: "green"
	}, {
		id: "bk",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Flag_of_Republic_of_Kosovo.svg/1000px-Flag_of_Republic_of_Kosovo.svg.png",
		icao: "BK",
		country: "Kosovo",
		link: "https://caa.rks-gov.net/en/category/aip-en/",
		aip: "green"
	}, {
		id: "ok",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/1000px-Flag_of_Kuwait.svg.png",
		icao: "OK",
		country: "Kuwait",
		link: "https://dgca.gov.kw/AIP",
		aip: "green"
	}, {
		id: "uc",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/1000px-Flag_of_Kyrgyzstan.svg.png",
		icao: "UC",
		country: "Kyrgistan",
		link: "http://kan.kg/en/ais",
		aip: "green"
	}, {
		id: "fm-reunion",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Proposed_flag_of_R%C3%A9union_%28ARF%29.svg/1024px-Proposed_flag_of_R%C3%A9union_%28ARF%29.svg.png",
		icao: "FM",
		country: "La Reunion",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "ev",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/1000px-Flag_of_Latvia.svg.png",
		icao: "EV",
		country: "Latvia",
		link: "https://ais.lgs.lv/#",
		aip: "green"
	}, {
		id: "ol",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/1000px-Flag_of_Lebanon.svg.png",
		icao: "OL",
		country: "Lebanon",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "fx",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/1000px-Flag_of_Lesotho.svg.png",
		icao: "FX",
		country: "Lesotho",
		link: "",
		aip: "red"
	}, {
		id: "hl",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/1000px-Flag_of_Libya.svg.png",
		icao: "HL",
		country: "Libya",
		link: "https://caa.gov.ly/ais/aip/",
		aip: "green"
	}, {
		id: "ey",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/1000px-Flag_of_Lithuania.svg.png",
		icao: "EY",
		country: "Lithuania",
		link: "https://www.ead.eurocontrol.int/cms-eadbasic/opencms/en/login/ead-basic/",
		aip: "green"
	}, {
		id: "el",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/1000px-Flag_of_Luxembourg.svg.png",
		icao: "EL",
		country: "Luxembourg",
		link: aipBelgiumLink,
		aip: "green"
	}, {
		id: "vm",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Flag_of_Macau.svg/1000px-Flag_of_Macau.svg.png",
		icao: "VM",
		country: "Macau",
		link: "https://www.aacm.gov.mo/reference_fly.php?pageid=98&lg=eng",
		aip: "green"
	}, {
		id: "fm-madagascar",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Madagascar.svg/1000px-Flag_of_Madagascar.svg.png",
		icao: "FM",
		country: "Madagascar",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "fw",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Flag_of_Malawi.svg/1000px-Flag_of_Malawi.svg.png",
		icao: "FW",
		country: "Malawi",
		link: "",
		aip: "red"
	}, {
		id: "wm",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/1000px-Flag_of_Malaysia.svg.png",
		icao: "WM",
		country: "Malaysia",
		link: "https://aip.caam.gov.my/aip/eAIP/history-en-MS.html",
		aip: "green"
	}, {
		id: "lm",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/1000px-Flag_of_Malta.svg.png",
		icao: "LM",
		country: "Malta",
		link: "https://www.transport.gov.mt/aviation/air-navigation-services-aerodromes/aeronautical-information-publication-3764",
		aip: "green"
	}, {
		id: "fi",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/1000px-Flag_of_Mauritius.svg.png",
		icao: "FI",
		country: "Mauritius",
		link: "https://civil-aviation.govmu.org/Pages/ANSPUBLICATION.aspx",
		aip: "green"
	}, {
		id: "fm-mayotte",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Mayotte_%28local%29.svg/1000px-Flag_of_Mayotte_%28local%29.svg.png",
		icao: "FM",
		country: "Mayotte",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "mm",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/1000px-Flag_of_Mexico.svg.png",
		icao: "MM",
		country: "Mexico",
		link: "https://aipmexico.seneam.gob.mx/inicio",
		aip: "green"
	}, {
		id: "lu",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/1000px-Flag_of_Moldova.svg.png",
		icao: "LU",
		country: "Moldova",
		link: "https://aim.moldatsa.md/#welcome",
		aip: "green"
	}, {
		id: "zm",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Mongolia.svg/1000px-Flag_of_Mongolia.svg.png",
		icao: "ZM",
		country: "Mongolia",
		link: "https://ais.mn/aipAip",
		aip: "green"
	}, {
		id: "fq",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Mozambique.svg/1000px-Flag_of_Mozambique.svg.png",
		icao: "FQ",
		country: "Mozambique",
		link: "",
		aip: "red"
	}, {
		id: "vy",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/1000px-Flag_of_Myanmar.svg.png",
		icao: "VY",
		country: "Myanmar",
		link: "https://www.ais.gov.mm/eAIP/history-en-GB.html",
		aip: "green"
	}, {
		id: "fy",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/1000px-Flag_of_Namibia.svg.png",
		icao: "FY",
		country: "Namibia",
		link: "http://www.dca.com.na/pubs/pubs.htm",
		aip: "green"
	}, {
		id: "an",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Flag_of_Nauru.svg/1000px-Flag_of_Nauru.svg.png",
		icao: "AN",
		country: "Nauru",
		link: pacificLink,
		aip: "green"
	}, {
		id: "vn",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/1000px-Flag_of_Nepal.svg.png",
		icao: "VN",
		country: "Nepal",
		link: "https://e-aip.caanepal.gov.np/",
		aip: "green"
	}, {
		id: "eh",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/1000px-Flag_of_the_Netherlands.svg.png",
		icao: "EH",
		country: "Netherlands",
		link: "https://en.lvnl.nl/information-for-airmen/publications-for-airmen",
		aip: "green"
	}, {
		id: "nz-newZealand",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/1000px-Flag_of_New_Zealand.svg.png",
		icao: "NZ",
		country: "New Zealand",
		link: "http://www.aip.net.nz/",
		aip: "green"
	}, {
		id: "nz-tokelau",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Flag_of_Tokelau.svg/1024px-Flag_of_Tokelau.svg.png",
		icao: "NZ",
		country: "Tokelau",
		link: "http://www.aip.net.nz/",
		aip: "green"
	}, {
		id: "dr",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Flag_of_Niger.svg/1000px-Flag_of_Niger.svg.png",
		icao: "DR",
		country: "Niger",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "dn",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/1000px-Flag_of_Nigeria.svg.png",
		icao: "DN",
		country: "Nigeria",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "as",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Norfolk_Island.svg/1000px-Flag_of_Norfolk_Island.svg.png",
		icao: "AS",
		country: "Norfolk Island",
		link: aipAustraliaLink,
		aip: "green"
	}, {
		id: "lw",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_North_Macedonia.svg/1000px-Flag_of_North_Macedonia.svg.png",
		icao: "LW",
		country: "North Macedonia",
		link: "https://ais.m-nav.info/eAIP/Start.htm",
		aip: "green"
	}, {
		id: "lc-northernCyprus",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Flag_of_the_Turkish_Republic_of_Northern_Cyprus.svg/1000px-Flag_of_the_Turkish_Republic_of_Northern_Cyprus.svg.png",
		icao: "LC",
		country: "Northern Cyprus",
		link: "http://havacilik.gov.ct.tr/en-us/-legislation/trnc-aip",
		aip: "green"
	}, {
		id: "en-norway",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/1000px-Flag_of_Norway.svg.png",
		icao: "EN",
		country: "Norway",
		link: "https://avinor.no/en/ais/",
		aip: "green"
	}, {
		id: "en-svalbard",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/1000px-Flag_of_Norway.svg.png",
		icao: "EN",
		country: "Svalbard (Spitzbergen)",
		link: "https://avinor.no/en/ais/",
		aip: "green"
	}, {
		id: "oo",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/1000px-Flag_of_Oman.svg.png",
		icao: "OO",
		country: "Oman",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "op",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/1000px-Flag_of_Pakistan.svg.png",
		icao: "OP",
		country: "Pakistan",
		link: "https://www.caapakistan.com.pk/AIS/AIS_AMDT.aspx",
		aip: "green"
	}, {
		id: "mp",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/1000px-Flag_of_Panama.svg.png",
		icao: "MP",
		country: "Panama",
		link: "https://www.aeronautica.gob.pa/",
		aip: "green"
	}, {
		id: "ay",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/1000px-Flag_of_Papua_New_Guinea.svg.png",
		icao: "AY",
		country: "Papua New Guinea",
		link: "https://www.niuskypacific.com.pg/publications/",
		aip: "green"
	}, {
		id: "sg",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/1000px-Flag_of_Paraguay.svg.png",
		icao: "SG",
		country: "Paraguay",
		link: "http://www.dinac.gov.py/v3/",
		aip: "green"
	}, {
		id: "ep",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/1000px-Flag_of_Poland.svg.png",
		icao: "EP",
		country: "Poland",
		link: "https://www.ais.pansa.pl/en/publications/aip-ifr/",
		aip: "green"
	}, {
		id: "ot",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/1000px-Flag_of_Qatar.svg.png",
		icao: "OT",
		country: "Qatar",
		link: "https://www.caa.gov.qa/en-us/Pages/AIM.aspx",
		aip: "green"
	}, {
		id: "lr",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/1000px-Flag_of_Romania.svg.png",
		icao: "LR",
		country: "Romania",
		link: "https://www.aisro.ro/",
		aip: "green"
	}, {
		id: "uu",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/1000px-Flag_of_Russia.svg.png",
		icao: "UU",
		country: "Russia",
		link: aipRussiaLink,
		aip: "green"
	}, {
		id: "hr",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/1000px-Flag_of_Rwanda.svg.png",
		icao: "HR",
		country: "Rwanda",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "fh-saintHelena",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Saint_Helena.svg/1000px-Flag_of_Saint_Helena.svg.png",
		icao: "FH",
		country: "Saint Helena",
		link: "https://atns.com/products-services/aim/aeronautical-information-managementst-helena-airport/7448",
		aip: "green"
	}, {
		id: "fp",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe.svg/1024px-Flag_of_S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe.svg.png",
		icao: "FP",
		country: "Sao Tome & Principe",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "oe",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/1000px-Flag_of_Saudi_Arabia.svg.png",
		icao: "OE",
		country: "Saudi Arabia",
		link: "https://sans.com.sa/English/Pages/Login.aspx?ReturnUrl=%2fEnglish%2fAIMs%2f_layouts%2f15%2fAuthenticate.aspx%3fSource%3d%252FEnglish%252FAIMs&Source=%2FEnglish%2FAIMs",
		aip: "green"
	}, {
		id: "ly-serbia",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/1024px-Flag_of_Serbia.svg.png",
		icao: "LY",
		country: "Serbia",
		link: aipSerbiaMontenegro,
		aip: "green"
	}, {
		id: "ly-montenegro",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Montenegro.svg/1024px-Flag_of_Montenegro.svg.png",
		icao: "LY",
		country: "Montenegro",
		link: aipSerbiaMontenegro,
		aip: "green"
	}, {
		id: "fs",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Seychelles.svg/1000px-Flag_of_Seychelles.svg.png",
		icao: "FS",
		country: "Seychelles",
		link: "https://www.scaa.sc/index.php/service-providers/aviation-services/e-ais",
		aip: "green"
	}, {
		id: "ws",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/1000px-Flag_of_Singapore.svg.png",
		icao: "WS",
		country: "Singapore",
		link: "https://aim-sg.caas.gov.sg/eaip.html",
		aip: "green"
	}, {
		id: "lz",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/1000px-Flag_of_Slovakia.svg.png",
		icao: "LZ",
		country: "Slovakia",
		link: "https://aim.lps.sk/web/",
		aip: "green"
	}, {
		id: "lj",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/1000px-Flag_of_Slovenia.svg.png",
		icao: "LJ",
		country: "Slovenia",
		link: "https://www.sloveniacontrol.si/acrobat/aip/Operations/history-en-GB.html",
		aip: "green"
	}, {
		id: "ag",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Solomon_Islands.svg/1000px-Flag_of_the_Solomon_Islands.svg.png",
		icao: "AG",
		country: "Solomon Islands",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "hc",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Somalia.svg/1000px-Flag_of_Somalia.svg.png",
		icao: "HC",
		country: "Somalia",
		link: "http://aip.scaa.gov.so/",
		aip: "green"
	}, {
		id: "fa",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/1000px-Flag_of_South_Africa.svg.png",
		icao: "FA",
		country: "South Africa",
		link: "http://www.caa.co.za/pages/aeronautical%20information/aeronautical%20information%20publication.aspx",
		aip: "green"
	}, {
		id: "le-spain",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/1000px-Flag_of_Spain.svg.png",
		icao: "LE",
		country: "Spain",
		link: "https://aip.enaire.es/AIP/AIP-en.html",
		aip: "green"
	}, {
		id: "vc",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/1000px-Flag_of_Sri_Lanka.svg.png",
		icao: "VC",
		country: "Sri Lanka",
		link: "https://www.airport.lk/aasl/AIS/web.Home.htm",
		aip: "green"
	}, {
		id: "es",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Sweden.svg/1000px-Flag_of_Sweden.svg.png",
		icao: "ES",
		country: "Sweden",
		link: "https://aro.lfv.se/Editorial/View/IAIP",
		aip: "green"
	}, {
		id: "rc",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/1000px-Flag_of_the_Republic_of_China.svg.png",
		icao: "RC",
		country: "Taiwan",
		link: "http://eaip.caa.gov.tw/eaip/home.faces",
		aip: "green"
	}, {
		id: "ut-tajikistan",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/1000px-Flag_of_Tajikistan.svg.png",
		icao: "UT",
		country: "Tajikistan",
		link: "http://www.caica.ru/aiptjk/validaip/index.htm",
		aip: "green"
	}, {
		id: "ft",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Chad.svg/1000px-Flag_of_Chad.svg.png",
		icao: "FT",
		country: "Chad",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "vt",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/1000px-Flag_of_Thailand.svg.png",
		icao: "VT",
		country: "Thailand",
		link: "https://aip.caat.or.th/",
		aip: "green"
	}, {
		id: "wp",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_East_Timor.svg/1000px-Flag_of_East_Timor.svg.png",
		icao: "WP",
		country: "Timor Leste",
		link: "https://aactl.gov.tl",
		aip: "green"
	}, {
		id: "dx",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Flag_of_Togo.svg/1000px-Flag_of_Togo.svg.png",
		icao: "DX",
		country: "Togo",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "fh-tristan",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Tristan_da_Cunha.svg/1000px-Flag_of_Tristan_da_Cunha.svg.png",
		icao: "FH",
		country: "Tristan da Cunha",
		link: "",
		aip: "black"
	}, {
		id: "dt",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/1000px-Flag_of_Tunisia.svg.png",
		icao: "DT",
		country: "Tunisia",
		link: "http://www.oaca.nat.tn/index.php?id=750&L=2",
		aip: "green"
	}, {
		id: "lt",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/1000px-Flag_of_Turkey.svg.png",
		icao: "LT",
		country: "Turkey",
		link: "https://www.dhmi.gov.tr/Sayfalar/aipturkey.aspx",
		aip: "green"
	}, {
		id: "ut-turkmenistan",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Turkmenistan.svg/1000px-Flag_of_Turkmenistan.svg.png",
		icao: "UT",
		country: "Turkmenistan",
		link: aipRussiaLink,
		aip: "green"
	},  {
		id: "hu",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/1000px-Flag_of_Uganda.svg.png",
		icao: "HU",
		country: "Uganda",
		link: "https://aim.caa.co.ug/eAIP",
		aip: "green"
	}, {
		id: "uk",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/1000px-Flag_of_Ukraine.svg.png",
		icao: "UK",
		country: "Ukraine",
		link: "http://aisukraine.net/titul_en.php",
		aip: "green"
	}, {
		id: "om",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/1000px-Flag_of_the_United_Arab_Emirates.svg.png",
		icao: "OM",
		country: "United Arab Emirates",
		link: "https://www.gcaa.gov.ae/aip/current/uae_aip.html",
		aip: "green"
	}, {
		id: "eg",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Flag_of_the_United_Kingdom_%281-2%29.svg/1024px-Flag_of_the_United_Kingdom_%281-2%29.svg.png",
		icao: "EG",
		country: "United Kingdom",
		link: aipUKLink,
		aip: "green"
	}, {
		id: "eg-england",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Flag_of_England.svg/1024px-Flag_of_England.svg.png",
		icao: "EG",
		country: "England",
		link: aipUKLink,
		aip: "green"
	}, {
		id: "eg-scotland",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Flag_of_Scotland.svg/1024px-Flag_of_Scotland.svg.png",
		icao: "EG",
		country: "Scotland",
		link: aipUKLink,
		aip: "green"
	}, {
		id: "eg-wales",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Flag_of_Wales.svg/1024px-Flag_of_Wales.svg.png",
		icao: "EG",
		country: "Wales",
		link: aipUKLink,
		aip: "green"
	}, {
		id: "eg-northernIreland",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Flag_of_Northern_Ireland_%281953%E2%80%931972%29.svg/1024px-Flag_of_Northern_Ireland_%281953%E2%80%931972%29.svg.png",
		icao: "EG",
		country: "Northern Ireland",
		link: aipUKLink,
		aip: "green"
	}, {
		id: "eg-jersey",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Flag_of_Jersey.svg/1024px-Flag_of_Jersey.svg.png",
		icao: "EG",
		country: "Jersey",
		link: aipUKLink,
		aip: "green"
	}, {
		id: "eg-guernsey",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Guernsey.svg/1024px-Flag_of_Guernsey.svg.png",
		icao: "EG",
		country: "Guernsey",
		link: aipUKLink,
		aip: "green"
	}, {
		id: "eg-isleOfMan",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_the_Isle_of_Man.svg/1024px-Flag_of_the_Isle_of_Man.svg.png",
		icao: "EG",
		country: "Isle of Man",
		link: aipUKLink,
		aip: "green"
	}, {
		id: "eg-sandwich",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_South_Georgia_and_the_South_Sandwich_Islands.svg/1024px-Flag_of_South_Georgia_and_the_South_Sandwich_Islands.svg.png",
		icao: "EG",
		country: "South Georgia and the South Sandwich Islands",
		link: "https://www.aidu.mod.uk/aip/aipVolumes.html#ad-tab",
		aip: "green"
	}, {
		id: "kd",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_the_U.S..svg/1000px-Flag_of_the_U.S..svg.png",
		icao: "KD",
		country: "United States of America",
		link: aipUSALink,
		aip: "green"
	}, {
		id: "su",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/1000px-Flag_of_Uruguay.svg.png",
		icao: "SU",
		country: "Uruguay",
		link: "https://www.dinacia.gub.uy/ais/aip-uruguay/english",
		aip: "green"
	}, {
		id: "ut-uzbekistan",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/1000px-Flag_of_Uzbekistan.svg.png",
		icao: "UT",
		country: "Uzbekistan",
		link: aipRussiaLink,
		aip: "green"
	},  {
		id: "sv",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Venezuela.svg/1000px-Flag_of_Venezuela.svg.png",
		icao: "SV",
		country: "Venezuela",
		link: "http://www.inac.gob.ve/eaip/history-en-GB.html",
		aip: "green"
	}, {
		id: "vv",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/1000px-Flag_of_Vietnam.svg.png",
		icao: "VV",
		country: "Vietnam",
		link: "https://vnaic.vn/index.php?option=com_content&view=category&id=53%3Aaip&layout=blog&Itemid=92&lang=en",
		aip: "green"
	}, {
		id: "fl",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/1000px-Flag_of_Zambia.svg.png",
		icao: "FL",
		country: "Zambia",
		link: "https://www.aim.zacl.co.zm/aip-publications",
		aip: "green"
	}, {
		id: "fv",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/1000px-Flag_of_Zimbabwe.svg.png",
		icao: "FV",
		country: "Zimbabwe",
		link: "",
        aip: "red"
	}, {
		id: "tt-anguilla",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Anguilla.svg/1024px-Flag_of_Anguilla.svg.png",
		icao: "TQ",
		country: "Anguilla",
		link: "https://caa.gov.tt/eastern-caribbean-eaip/",
        aip: "green"
	}, {
		id: "tt-antigua",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/1024px-Flag_of_Antigua_and_Barbuda.svg.png",
		icao: "TA",
		country: "Antigua & Barbuda",
		link: "https://caa.gov.tt/eastern-caribbean-eaip/",
        aip: "green"
	}, {
		id: "tt-british",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_the_British_Virgin_Islands.svg/1024px-Flag_of_the_British_Virgin_Islands.svg.png",
		icao: "TU",
		country: "British Virgin Islands",
		link: "https://caa.gov.tt/eastern-caribbean-eaip/",
        aip: "green"
	}, {
		id: "tt-dominica",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Flag_of_Dominica.svg/1024px-Flag_of_Dominica.svg.png",
		icao: "TD",
		country: "Dominica",
		link: "https://caa.gov.tt/eastern-caribbean-eaip/",
        aip: "green"
	}, {
		id: "tt-grenada",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Grenada.svg/1024px-Flag_of_Grenada.svg.png",
		icao: "TG",
		country: "Grenada",
		link: "https://caa.gov.tt/eastern-caribbean-eaip/",
        aip: "green"
	}, {
		id: "tt-montserrat",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Montserrat.svg/1024px-Flag_of_Montserrat.svg.png",
		icao: "TR",
		country: "Montserrat",
		link: "https://caa.gov.tt/eastern-caribbean-eaip/",
        aip: "green"
	}, {
		id: "tt-stkitts",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Flag_of_Saint_Christopher-Nevis-Anguilla.svg/1024px-Flag_of_Saint_Christopher-Nevis-Anguilla.svg.png",
		icao: "TK",
		country: "Saint Kitts and Nevis",
		link: "https://caa.gov.tt/eastern-caribbean-eaip/",
        aip: "green"
	}, {
		id: "tt-stlucia",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Saint_Lucia.svg/1024px-Flag_of_Saint_Lucia.svg.png",
		icao: "TL",
		country: "Saint Lucia",
		link: "https://caa.gov.tt/eastern-caribbean-eaip/",
        aip: "green"
	}, {
		id: "tt-stvincent",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg/1024px-Flag_of_Saint_Vincent_and_the_Grenadines.svg.png",
		icao: "TV",
		country: "Saint Vincent and the Grenadines",
		link: "https://caa.gov.tt/eastern-caribbean-eaip/",
        aip: "green"
	}, {
		id: "tt-trinidad",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Trinidad_and_Tobago.svg/1024px-Flag_of_Trinidad_and_Tobago.svg.png",
		icao: "TT",
		country: "Trinidad and Tobago",
		link: "https://caa.gov.tt/eastern-caribbean-eaip/",
        aip: "green"
	}, {
		id: "tt-caribbean",
		img: "http://www.eccaa.aero/templates/at_galeta/images/color3/logo.png",
		icao: "TT",
		country: "Eastern Caribbean",
		link: "https://caa.gov.tt/eastern-caribbean-eaip/",
        aip: "green"
	}, {
		id: "lp-portugal",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/1024px-Flag_of_Portugal.svg.png",
		icao: "LP",
		country: "Portugal",
		link: "https://www.nav.pt/en/ais/eaip",
        aip: "green"
	}, {
		id: "lp-azores",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Flag_of_the_Azores.svg/1024px-Flag_of_the_Azores.svg.png",
		icao: "LP",
		country: "Azores",
		link: "https://www.nav.pt/en/ais/eaip",
        aip: "green"
	}, {
		id: "lp-madeira",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_Madeira.svg/1024px-Flag_of_Madeira.svg.png",
		icao: "LP",
		country: "Madeira",
		link: "https://www.nav.pt/en/ais/eaip",
        aip: "green"
	}, {
		id: "my",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_the_Bahamas.svg/1024px-Flag_of_the_Bahamas.svg.png",
		icao: "MY",
		country: "Bahamas",
		link: toolboxeaipLink,
        aip: "yellow"
	}, {
		id: "mr",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Costa_Rica.svg/1024px-Flag_of_Costa_Rica.svg.png",
		icao: "MR",
		country: "Costa Rica",
		link: "https://www.dgac.go.cr/servicio/aismap/",
        aip: "green"
	}, {
		id: "mz",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Flag_of_Belize.svg/1024px-Flag_of_Belize.svg.png",
		icao: "MZ",
		country: "Belize",
		link: cocesnaLink,
        aip: "green"
	}, {
		id: "ms",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/1024px-Flag_of_El_Salvador.svg.png",
		icao: "MS",
		country: "El Salvador",
		link: cocesnaLink,
        aip: "green"
	}, {
		id: "mn",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Nicaragua.svg/1024px-Flag_of_Nicaragua.svg.png",
		icao: "MN",
		country: "Nicaragua",
		link: cocesnaLink,
        aip: "green"
	}, {
		id: "mg",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Flag_of_Guatemala.svg/1024px-Flag_of_Guatemala.svg.png",
		icao: "MG",
		country: "Guatemala",
		link: cocesnaLink,
        aip: "green"
	}, {
		id: "mh-cocesna",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Flag_of_the_Central_American_Integration_System.svg/1024px-Flag_of_the_Central_American_Integration_System.svg.png",
		icao: "MH",
		country: "COCESNA",
		link: cocesnaLink,
        aip: "green"
    }, {
		id: "fm-asecna",
		img: "https://aim.asecna.aero/html/images/logo_asecna.png",
		icao: "FM",
		country: "ASECNA",
		link: asecnaLink,
        aip: "green"
    }, {
		id: "tn-dcansp",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_the_Netherlands_Antilles.png/1024px-Flag_of_the_Netherlands_Antilles.png",
		icao: "TN",
		country: "Dutch Caribbean",
		link: dutchCaribbeanLink,
        aip: "green"
    }, {
		id: "tn-aruba",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Aruba.svg/1024px-Flag_of_Aruba.svg.png",
		icao: "TN",
		country: "Aruba",
		link: dutchCaribbeanLink,
        aip: "green"
    }, {
		id: "tn-bonaire",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Flag_of_Bonaire.svg/1024px-Flag_of_Bonaire.svg.png",
		icao: "TN",
		country: "Bonaire",
		link: dutchCaribbeanLink,
        aip: "green"
    }, {
		id: "tn-curacao",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_Cura%C3%A7ao.svg/1024px-Flag_of_Cura%C3%A7ao.svg.png",
		icao: "TN",
		country: "Curacao",
		link: dutchCaribbeanLink,
        aip: "green"
    }, {
		id: "tn-saba",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Flag_of_Saba.svg/1024px-Flag_of_Saba.svg.png",
		icao: "TN",
		country: "Saba",
		link: dutchCaribbeanLink,
        aip: "green"
    }, {
		id: "tn-eustatius",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Flag_of_Sint_Eustatius.svg/1024px-Flag_of_Sint_Eustatius.svg.png",
		icao: "TN",
		country: "Sint Eustatius",
		link: dutchCaribbeanLink,
        aip: "green"
    }, {
		id: "tn-marteen",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Sint_Maarten.svg/1024px-Flag_of_Sint_Maarten.svg.png",
		icao: "TN",
		country: "Sint Marteen",
		link: dutchCaribbeanLink,
        aip: "green"
    }, {
		id: "nf-pacific",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_the_Pacific_Community.svg/1024px-Flag_of_the_Pacific_Community.svg.png",
		icao: "NF",
		country: "South Pacific",
		link: pacificLink,
        aip: "green"
    }, {
		id: "ni",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Niue.svg/1024px-Flag_of_Niue.svg.png",
		icao: "NI",
		country: "Niue",
		link: pacificLink,
        aip: "green"
    }, {
		id: "ns-samoapacific",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Samoa.svg/1024px-Flag_of_Samoa.svg.png",
		icao: "NS",
		country: "Samoa",
		link: pacificLink,
        aip: "green"
    }, {
		id: "ns-samoausa",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Flag_of_American_Samoa.svg/1024px-Flag_of_American_Samoa.svg.png",
		icao: "NS",
		country: "American Samoa",
		link: aipUSALink,
        aip: "green"
    }, {
		id: "nf-tonga",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Tonga.svg/1024px-Flag_of_Tonga.svg.png",
		icao: "NF",
		country: "Tonga",
		link: pacificLink,
        aip: "green"
    }, {
		id: "ng",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tuvalu.svg/1024px-Flag_of_Tuvalu.svg.png",
		icao: "NG",
		country: "Tuvalu",
		link: pacificLink,
        aip: "green"
    }, {
		id: "nv",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Vanuatu.svg/1024px-Flag_of_Vanuatu.svg.png",
		icao: "NV",
		country: "Vanuatu",
		link: pacificLink,
        aip: "green"
    }, {
		id: "wb-brunei",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/1024px-Flag_of_Brunei.svg.png",
		icao: "WB",
		country: "Brunei",
		link: "http://www.dca.gov.bn/AIP/Forms/AllItems.aspx",
        aip: "green"
    }, {
		id: "hb",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/1024px-Flag_of_Burundi.svg.png",
		icao: "HB",
		country: "Burundi",
		link: "",
        aip: "red"
    }, {
		id: "gv",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/1024px-Flag_of_Cape_Verde.svg.png",
		icao: "GV",
		country: "Cabo Verde",
		link: "https://ais.asa.cv/",
        aip: "green"
    }, {
		id: "pt-caroline",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg/1024px-Flag_of_the_Federated_States_of_Micronesia.svg.png",
		icao: "PT",
		country: "Caroline Islands",
		link: aipUSALink,
        aip: "green"
    }, {
		id: "pt-micronesia",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg/1024px-Flag_of_the_Federated_States_of_Micronesia.svg.png",
		icao: "PT",
		country: "Micronesia",
		link: aipUSALink,
        aip: "green"
    }, {
		id: "pt-palau",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Palau.svg/1024px-Flag_of_Palau.svg.png",
		icao: "PT",
		country: "Palau",
		link: aipUSALink,
        aip: "green"
    }, {
        id: "pc",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kiribati.svg/1024px-Flag_of_Kiribati.svg.png",
		icao: "PC",
		country: "Kiribati",
		link: pacificLink,
        aip: "green"
    }, {
		id: "ge-ceuta",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_Ceuta.svg/1024px-Flag_Ceuta.svg.png",
		icao: "GE",
		country: "Ceuta",
		link: "https://aip.enaire.es/AIP/AIP-en.html",
        aip: "green"
    }, {
		id: "hd",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Djibouti.svg/1024px-Flag_of_Djibouti.svg.png",
		icao: "HD",
		country: "Djibouti",
		link: "",
        aip: "red"
    }, {
		id: "hh",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Eritrea.svg/1024px-Flag_of_Eritrea.svg.png",
		icao: "HH",
		country: "Eritrea",
		link: "",
        aip: "red"
    }, {
		id: "ha",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/1024px-Flag_of_Ethiopia.svg.png",
		icao: "HA",
		country: "Ethiopia",
		link: "",
        aip: "red"
    }, {
		id: "sf",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_Falkland_Islands.svg/1024px-Flag_of_the_Falkland_Islands.svg.png",
		icao: "SF",
		country: "Falkland Islands",
		link: "",
        aip: "black"
    }, {
		id: "nf",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Fiji.svg/1024px-Flag_of_Fiji.svg.png",
		icao: "NF",
		country: "Fiji",
		link: "http://airportsfiji.com/ais-fiji/wp-login.php?redirect_to=http%3A%2F%2Fairportsfiji.com%2Fais-fiji",
        aip: "green"
    }, {
		id: "so",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_French_Guiana.svg/1024px-Flag_of_French_Guiana.svg.png",
		icao: "SO",
		country: "French Guiana",
		link: aipFranceLink,
        aip: "green"
    }, {
		id: "nt-poly",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Flag_of_French_Polynesia.svg/1024px-Flag_of_French_Polynesia.svg.png",
		icao: "NT",
		country: "French Polynesia",
		link: aipFranceLink,
        aip: "green"
    }, {
		id: "nt-pitcairn",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_the_Pitcairn_Islands.svg/1024px-Flag_of_the_Pitcairn_Islands.svg.png",
		icao: "NT",
		country: "Pitcairn Islands",
		link: "",
        aip: "black"
    }, {
		id: "nl-futuna",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Flag_of_Wallis_and_Futuna.svg/1024px-Flag_of_Wallis_and_Futuna.svg.png",
		icao: "NL",
		country: "Futuna Islands",
		link: aipFranceLink,
        aip: "green"
    }, {
		id: "nl-wallis",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Flag_of_Wallis_and_Futuna.svg/1024px-Flag_of_Wallis_and_Futuna.svg.png",
		icao: "NL",
		country: "Wallis",
		link: aipFranceLink,
        aip: "green"
    }, {
		id: "lx",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Flag_of_Gibraltar.svg/1024px-Flag_of_Gibraltar.svg.png",
		icao: "LX",
		country: "Gibraltar",
		link: "https://www.aidu.mod.uk/aip/",
        aip: "green"
    }, {
		id: "tf",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Unofficial_flag_of_Guadeloupe_%28local%29.svg/1024px-Unofficial_flag_of_Guadeloupe_%28local%29.svg.png",
		icao: "TF",
		country: "Guadeloupe",
		link: aipFranceLink,
        aip: "green"
    }, {
		id: "pg-guam",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Flag_of_Guam.svg/1024px-Flag_of_Guam.svg.png",
		icao: "PG",
		country: "Guam",
		link: aipUSALink,
        aip: "green"
    }, {
		id: "pg-mariana",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Flag_of_the_Northern_Mariana_Islands.svg/1024px-Flag_of_the_Northern_Mariana_Islands.svg.png",
		icao: "PG",
		country: "Northen Mariana Island",
		link: aipUSALink,
        aip: "green"
    }, {
		id: "gu",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_Guinea.svg/1024px-Flag_of_Guinea.svg.png",
		icao: "GU",
		country: "Guinea",
		link: "",
        aip: "red"
    }, {
		id: "gg",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Guinea-Bissau.svg/1024px-Flag_of_Guinea-Bissau.svg.png",
		icao: "GG",
		country: "Guinea Bissau",
		link: asecnaLink,
        aip: "green"
    }, {
		id: "sy",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_Guyana.svg/1024px-Flag_of_Guyana.svg.png",
		icao: "SY",
		country: "Guyana",
		link: "https://www.gcaa-gy.org/guyana-aip.html",
        aip: "green"
    }, {
		id: "mk",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/1024px-Flag_of_Jamaica.svg.png",
		icao: "MK",
		country: "Jamaica",
		link: "https://aim.jcaa.aero/client/login",
        aip: "green"
    }, {
		id: "vl",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Laos.svg/1024px-Flag_of_Laos.svg.png",
		icao: "VL",
		country: "Laos",
		link: "",
        aip: "red"
    }, {
		id: "gl",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Flag_of_Liberia.svg/1024px-Flag_of_Liberia.svg.png",
		icao: "GL",
		country: "Liberia",
		link: "",
        aip: "red"
    }, {
		id: "ls-liechtenstein",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/1024px-Flag_of_Liechtenstein.svg.png",
		icao: "LS",
		country: "Liechtenstein",
		link: aipSwitzerlandLink,
        aip: "green"
    }, {
        id: "pl-us",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_the_U.S..svg/1000px-Flag_of_the_U.S..svg.png",
		icao: "PL",
		country: "US Line Islands",
		link: aipUSALink,
        aip: "green"
    }, {
        id: "pl-us-palmyra",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_the_U.S..svg/1000px-Flag_of_the_U.S..svg.png",
		icao: "PL",
		country: "Palmyra Atoll",
		link: aipUSALink,
        aip: "green"
    }, {
        id: "pl-pc",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kiribati.svg/1024px-Flag_of_Kiribati.svg.png",
		icao: "PL",
		country: "Kiribati Line Islands",
		link: pacificLink,
        aip: "green"
    }, {
        id: "pl-pc-christmas",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Flag_of_Christmas_Island.svg/1024px-Flag_of_Christmas_Island.svg.png",
		icao: "PL",
		country: "Kirimati (Christmas Island)",
		link: pacificLink,
        aip: "green"
    },  {
        id: "vr",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Maldives.svg/1024px-Flag_of_Maldives.svg.png",
		icao: "VR",
		country: "Maldives",
		link: "https://www.macl.aero/corporate/services/operational/ans",
        aip: "green"
    }, {
        id: "ga",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Mali.svg/1024px-Flag_of_Mali.svg.png",
		icao: "GA",
		country: "Mali",
		link: asecnaLink,
        aip: "green"
    }, {
        id: "pk",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Flag_of_the_Marshall_Islands.svg/1024px-Flag_of_the_Marshall_Islands.svg.png",
		icao: "PK",
		country: "Marshall Islands",
		link: aipUSALink,
        aip: "green"
    }, {
        id: "tf-martinique",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag-of-Martinique.svg/1024px-Flag-of-Martinique.svg.png",
		icao: "TF",
		country: "Martinique",
		link: aipFranceLink,
        aip: "green"
    }, {
        id: "tf-barthelemy",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Saint_Barth%C3%A9lemy_%28local%29.svg/1024px-Flag_of_Saint_Barth%C3%A9lemy_%28local%29.svg.png",
		icao: "TF",
		country: "Saint Barthelemy",
		link: aipFranceLink,
        aip: "green"
    }, {
        id: "tf-martin",
		img: "https://upload.wikimedia.org/wikipedia/commons/9/94/Flag_of_Saint_Martin_%28local%29.gif",
		icao: "TF",
		country: "Saint Martin",
		link: aipFranceLink,
        aip: "green"
    }, {
        id: "gq",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Flag_of_Mauritania.svg/1024px-Flag_of_Mauritania.svg.png",
		icao: "GQ",
		country: "Mauritania",
		link: asecnaLink,
        aip: "green"
    }, {
        id: "ge-melilla",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Flag_of_Melilla.svg/1024px-Flag_of_Melilla.svg.png",
		icao: "GE",
		country: "Melilla",
		link: "https://aip.enaire.es/AIP/AIP-en.html",
        aip: "green"
    }, {
        id: "gc",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Flag_of_the_Canary_Islands.svg/1024px-Flag_of_the_Canary_Islands.svg.png",
		icao: "GC",
		country: "Canary Islands",
		link: "https://aip.enaire.es/AIP/AIP-en.html",
        aip: "green"
    }, {
		id: "pm",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Flag_of_the_Midway_Islands_%28local%29.svg/1024px-Flag_of_the_Midway_Islands_%28local%29.svg.png",
		icao: "PM",
		country: "Midway Atoll",
		link: aipUSALink,
        aip: "green"
    }, {
		id: "ln",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Monaco.svg/1280px-Flag_of_Monaco.svg.png",
		icao: "LN",
		country: "Monaco",
		link: aipFranceLink,
        aip: "green"
    }, {
		id: "gm",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/1024px-Flag_of_Morocco.svg.png",
		icao: "GM",
		country: "Morocco",
		link: "http://siamaroc.onda.ma/",
        aip: "green"
    }, {
		id: "nw",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_New_Caledonia_%28WFB_2000%29.svg/1024px-Flag_of_New_Caledonia_%28WFB_2000%29.svg.png",
		icao: "NW",
		country: "New Caledonia",
		link: aipFranceLink,
        aip: "green"
    }, {
		id: "zk",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Flag_of_North_Korea.svg/1024px-Flag_of_North_Korea.svg.png",
		icao: "ZK",
		country: "North Korea",
		link: "",
        aip: "red"
    }, {
		id: "lv",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/1024px-Flag_of_Palestine.svg.png",
		icao: "LV",
		country: "Palestine / Gaza Strip",
		link: "",
        aip: "black"
    }, {
		id: "sp",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/1024px-Flag_of_Peru.svg.png",
		icao: "SP",
		country: "Peru",
		link: "http://portal2.corpac.gob.pe/SSO",
        aip: "green"
    }, {
		id: "rp",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/1024px-Flag_of_the_Philippines.svg.png",
		icao: "RP",
		country: "Philippines",
		link: "",
        aip: "red"
    }, {
		id: "tj",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/1024px-Flag_of_Puerto_Rico.svg.png",
		icao: "TJ",
		country: "Puerto Rico",
		link: aipUSALink,
        aip: "green"
    }, {
		id: "go",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/1024px-Flag_of_Senegal.svg.png",
		icao: "GO",
		country: "Senegal",
		link: asecnaLink,
        aip: "green"
    }, {
		id: "gf",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Sierra_Leone.svg/1024px-Flag_of_Sierra_Leone.svg.png",
		icao: "GF",
		country: "Sierra Leone",
		link: "",
        aip: "red"
    }, {
		id: "hs-sudan",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/1024px-Flag_of_Sudan.svg.png",
		icao: "HS",
		country: "Sudan",
		link: "",
        aip: "red"
    }, {
		id: "hs-southSudan",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Flag_of_South_Sudan.svg/1024px-Flag_of_South_Sudan.svg.png",
		icao: "HS",
		country: "South Sudan",
		link: toolboxeaipLink,
        aip: "yellow"
    }, {
		id: "sm",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Flag_of_Suriname.svg/1024px-Flag_of_Suriname.svg.png",
		icao: "SM",
		country: "Suriname",
		link: "",
        aip: "red"
    }, {
		id: "os",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Flag_of_Syria.svg/1024px-Flag_of_Syria.svg.png",
		icao: "OS",
		country: "Syria",
		link: "",
        aip: "red"
    }, {
		id: "ht",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/1024px-Flag_of_Tanzania.svg.png",
		icao: "HT",
		country: "Tanzania",
		link: toolboxeaipLink,
        aip: "yellow"
    }, {
		id: "mb",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg/1024px-Flag_of_the_Turks_and_Caicos_Islands.svg.png",
		icao: "MB",
		country: "Turks and Caicos Islands",
		link: "https://tciairports.com/aip-supplement/",
        aip: "green"
    }, {
		id: "ti",
		img: "https://upload.wikimedia.org/wikipedia/commons/9/94/Flag_of_Virgin_Islands.jpg",
		icao: "TI",
		country: "US Virgin Islands",
		link: aipUSALink,
        aip: "green"
    }, {
		id: "pw",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Wake_Island.svg/1024px-Flag_of_Wake_Island.svg.png",
		icao: "PW",
		country: "Wake Island",
		link: aipUSALink,
        aip: "green"
    }, {
		id: "gs",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg/1024px-Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg.png",
		icao: "GS",
		country: "Western Sahara",
		link: "",
        aip: "black"
    }, {
		id: "oy",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Yemen.svg/1024px-Flag_of_Yemen.svg.png",
		icao: "OY",
		country: "Yemen",
		link: "",
        aip: "red"
    },
	{
		id: "oj-west_bank",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/1024px-Flag_of_Palestine.svg.png",
		icao: "OJ",
		country: "West Bank",
		link: "http://www.carc.gov.jo/en/ais",
		aip: "green",
	},
	{
		id: "kd-kingman_reef",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Unofficial_flag_of_Kingman_Reef.svg/1024px-Unofficial_flag_of_Kingman_Reef.svg.png",
		icao: "KD",
		country: "Kingman Reef",
		link: aipUSALink,
		aip: "green",
	},
	{
		id: "kd-johnston_atoll",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Flag_of_Johnston_Atoll_%28local%29.svg/1024px-Flag_of_Johnston_Atoll_%28local%29.svg.png",
		icao: "KD",
		country: "Johnston Atoll",
		link: aipUSALink,
		aip: "green",
	},
	{
		id: "kd-howland_island",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Unofficial_Flag_of_Howland%2C_Baker%2C_and_Jarvis_Islands.svg/1024px-Unofficial_Flag_of_Howland%2C_Baker%2C_and_Jarvis_Islands.svg.png",
		icao: "KD",
		country: "Howland Island",
		link: aipUSALink,
		aip: "green",
	},
	{
		id: "kd-baker_island",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Unofficial_Flag_of_Howland%2C_Baker%2C_and_Jarvis_Islands.svg/1024px-Unofficial_Flag_of_Howland%2C_Baker%2C_and_Jarvis_Islands.svg.png",
		icao: "KD",
		country: "Baker Island",
		link: aipUSALink,
		aip: "green",
	},
	{
		id: "kd-jarvis_island",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Unofficial_Flag_of_Howland%2C_Baker%2C_and_Jarvis_Islands.svg/1024px-Unofficial_Flag_of_Howland%2C_Baker%2C_and_Jarvis_Islands.svg.png",
		icao: "KD",
		country: "Jarvis Island",
		link: aipUSALink,
		aip: "green",
	},
	{
		id: "yb-ashmore_cartier",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/1000px-Flag_of_Australia.svg.png",
		icao: "YB",
		country: "Ashmore and Cartier Islands",
		link: aipAustraliaLink,
		aip: "green",
	},
	{
		id: "fa-bouvet_island",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Flag_Bouvet_island.png/1024px-Flag_Bouvet_island.png",
		icao: "FA",
		country: "Bouvet Island",
		link: "http://www.caa.co.za/pages/aeronautical%20information/aeronautical%20information%20publication.aspx",
		aip: "green",
	},
];
