const toolboxeaipLink   = "http://ais.skyguide.corp/map/eaipbytable.html";
const asecnaLink        = "https://aim.asecna.aero/html/index-fr-FR.html";
const aipDenmarkLink    = "https://aim.naviair.dk/en/";
const aipFranceLink     = "https://www.sia.aviation-civile.gouv.fr/";
const aipBelgiumLink    = "https://ops.skeyes.be/html/belgocontrol_static/eaip/eAIP_Product/index.html";
const aipRussiaLink     = "http://www.caiga.ru/common/?lang=en";
const aipAustraliaLink  = "https://www.airservicesaustralia.com/aip/aip.asp";

const aipTileData = [{
		id: "oa",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Afghanistan.svg/900px-Flag_of_Afghanistan.svg.png",
		icao: "OA",
		country: "Afghanistan",
		link: "http://acaa.gov.af/aip-aeronautical-information-publication/",
		aip: "green"
	}, {
		id: "da",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/900px-Flag_of_Algeria.svg.png",
		icao: "DA",
		country: "Algeria",
		link: "https://www.sia-enna.dz/",
		aip: "green"
	}, {
		id: "la",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/900px-Flag_of_Albania.svg.png",
		icao: "LA",
		country: "Albania",
		link: "https://albcontrol.al/al/aip/",
		aip: "green"
	}, {
		id: "fn",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/900px-Flag_of_Angola.svg.png",
		icao: "FN",
		country: "Angola",
		link: "http://www.inavic.gv.ao/opencms/inavicsite/sia/",
		aip: "green"
	}, {
		id: "sa",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/1000px-Flag_of_Argentina.svg.png",
		icao: "SA",
		country: "Argentina",
		link: "http://ais.anac.gov.ar/aip",
		aip: "green"
	}, {
		id: "ud",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/1000px-Flag_of_Armenia.svg.png",
		icao: "UD",
		country: "Armenia",
		link: "http://www.armats.am/activities/ais/eaip",
		aip: "green"
	}, {
		id: "tn",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Aruba.svg/1000px-Flag_of_Aruba.svg.png",
		icao: "TN",
		country: "Aruba",
		link: "http://dc-ansp.org/eAIS/about-ais/",
		aip: "green"
	}, {
		id: "fh-ascension",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Ascension_Island.svg/1000px-Flag_of_Ascension_Island.svg.png",
		icao: "FH",
		country: "Ascension Island",
		link: "",
		aip: "black"
	}, {
		id: "yb",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/1000px-Flag_of_Australia.svg.png",
		icao: "YB",
		country: "Australia",
		link: aipAustraliaLink,
		aip: "green"
	}, {
		id: "lo",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/1000px-Flag_of_Austria.svg.png",
		icao: "LO",
		country: "Austria",
		link: "https://eaip.austrocontrol.at/",
		aip: "green"
	}, {
		id: "ub",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1000px-Flag_of_Azerbaijan.svg.png",
		icao: "UB",
		country: "Azerbaijan",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "ob",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/1000px-Flag_of_Bahrain.svg.png",
		icao: "OB",
		country: "Bahrain",
		link: "http://www.bahrainaims.com/aip_button.html",
		aip: "green"
	}, {
		id: "vg",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/1000px-Flag_of_Bangladesh.svg.png",
		icao: "VG",
		country: "Bangladesh",
		link: "http://www.caab.gov.bd/aip/index.html",
		aip: "green"
	}, {
		id: "tb",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/1000px-Flag_of_Barbados.svg.png",
		icao: "TB",
		country: "Barbados",
		link: "http://bcad.gov.bb/eAIP/bcad/index.php",
		aip: "green"
	}, {
		id: "eb-belgium",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/1000px-Flag_of_Belgium.svg.png",
		icao: "EB",
		country: "Belgium",
		link: aipBelgiumLink,
		aip: "green"
	}, {
		id: "um",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/1000px-Flag_of_Belarus.svg.png",
		icao: "UM",
		country: "Belarus",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "db",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/1000px-Flag_of_Benin.svg.png",
		icao: "DB",
		country: "Benin",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "tx",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bermuda.svg/1000px-Flag_of_Bermuda.svg.png",
		icao: "TX",
		country: "Bermuda",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "vq",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/1000px-Flag_of_Bhutan.svg.png",
		icao: "VQ",
		country: "Bhutan",
		link: "https://www.doat.gov.bt/aip/",
		aip: "green"
	}, {
		id: "lq",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/1000px-Flag_of_Bosnia_and_Herzegovina.svg.png",
		icao: "LQ",
		country: "Bosnia & Herzegowina",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "sl",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bandera_de_Bolivia_%28Estado%29.svg/1000px-Bandera_de_Bolivia_%28Estado%29.svg.png",
		icao: "SL",
		country: "Bolivia",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "fb",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/1000px-Flag_of_Botswana.svg.png",
		icao: "FB",
		country: "Botswana",
		link: "",
		aip: "red"
	}, {
		id: "fj",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_the_Commissioner_of_the_British_Indian_Ocean_Territory.svg/1000px-Flag_of_the_Commissioner_of_the_British_Indian_Ocean_Territory.svg.png",
		icao: "FJ",
		country: "British Indian Ocean Territory",
		link: "",
		aip: "black"
	}, {
		id: "lb",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/1000px-Flag_of_Bulgaria.svg.png",
		icao: "LB",
		country: "Bulgaria",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "df",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/1000px-Flag_of_Burkina_Faso.svg.png",
		icao: "DF",
		country: "Burkina Faso",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "sb",
		img: "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/1024px-Flag_of_Brazil.svg.png",
		icao: "SB",
		country: "Brazil",
		link: "https://aisweb.decea.mil.br/",
		aip: "green"
	}, {
		id: "vd",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/1000px-Flag_of_Cambodia.svg.png",
		icao: "VD",
		country: "Cambodia",
		link: "http://www.civilaviation.gov.kh/en",
		aip: "green"
	}, {
		id: "fk",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/1000px-Flag_of_Cameroon.svg.png",
		icao: "FK",
		country: "Cameroon",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "cy",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Canada.svg/1000px-Flag_of_Canada.svg.png",
		icao: "CY",
		country: "Canada",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "mw",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_the_Cayman_Islands.svg/1000px-Flag_of_the_Cayman_Islands.svg.png",
		icao: "MW",
		country: "Cayman Islands",
		link: "https://www.caymanairports.com/aeronautical-information-publication/",
		aip: "green"
	}, {
		id: "fe",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Central_African_Republic.svg/1000px-Flag_of_the_Central_African_Republic.svg.png",
		icao: "FE",
		country: "Central African Republic",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "sc",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/1000px-Flag_of_Chile.svg.png",
		icao: "SC",
		country: "Chile",
		link: "https://aipchile.dgac.gob.cl/",
		aip: "green"
	}, {
		id: "zb",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/1000px-Flag_of_the_People%27s_Republic_of_China.svg.png",
		icao: "ZB",
		country: "China",
		link: "http://www.eaipchina.cn/",
		aip: "green"
	}, {
		id: "sk",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/1000px-Flag_of_Colombia.svg.png",
		icao: "SK",
		country: "Colombia",
		link: "https://www.aerocivil.gov.co/servicios-a-la-navegacion/servicio-de-informacion-aeronautica-ais/aip",
		aip: "green"
	}, {
		id: "fm-comoros",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/1000px-Flag_of_the_Comoros.svg.png",
		icao: "FM",
		country: "Comoros",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "fc",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Republic_of_the_Congo.svg/1000px-Flag_of_the_Republic_of_the_Congo.svg.png",
		icao: "FC",
		country: "Congo",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "nc",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Flag_of_the_Cook_Islands.svg/1000px-Flag_of_the_Cook_Islands.svg.png",
		icao: "NC",
		country: "Cook Islands",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "ld",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Flag_of_Croatia_at_the_UN.svg/1000px-Flag_of_Croatia_at_the_UN.svg.png",
		icao: "LD",
		country: "Croatia",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "mu",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/1000px-Flag_of_Cuba.svg.png",
		icao: "MU",
		country: "Cuba",
		link: "https://aismet.avianet.cu/html/aip.html",
		aip: "green"
	}, {
		id: "lc-cyprus",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/1000px-Flag_of_Cyprus.svg.png",
		icao: "LC",
		country: "Cyprus",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "lk",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/1000px-Flag_of_the_Czech_Republic.svg.png",
		icao: "LK",
		country: "Czech Rebulic",
		link: "https://aim.rlp.cz/",
		aip: "green"
	}, {
		id: "fz",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/1024px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png",
		icao: "FZ",
		country: "Democratic Republic of Congo",
		link: "",
		aip: "red"
	}, {
		id: "ek",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/1000px-Flag_of_Denmark.svg.png",
		icao: "EK",
		country: "Denmark",
		link: aipDenmarkLink,
		aip: "green"
	}, {
		id: "md",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/1000px-Flag_of_the_Dominican_Republic.svg.png",
		icao: "MD",
		country: "Dominican Republic",
		link: "https://aip.idac.gob.do/Aip/IndexAip",
		aip: "green"
	}, {
		id: "se",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/1000px-Flag_of_Ecuador.svg.png",
		icao: "SE",
		country: "Ecuador",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "fg",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Equatorial_Guinea.svg/1000px-Flag_of_Equatorial_Guinea.svg.png",
		icao: "FG",
		country: "Equatorial Guinea",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "ee",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Estonia.png/1024px-Flag_of_Estonia.png",
		icao: "EE",
		country: "Estonia",
		link: "https://aim.eans.ee/en/eaip",
		aip: "green"
	}, {
		id: "fd",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Eswatini.svg/1000px-Flag_of_Eswatini.svg.png",
		icao: "FD",
		country: "eSwatini",
		link: "",
		aip: "red"
	}, {
		id: "he",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/1000px-Flag_of_Egypt.svg.png",
		icao: "HE",
		country: "Egypt",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "ek-faroer",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Flag_of_the_Faroe_Islands.svg/1000px-Flag_of_the_Faroe_Islands.svg.png",
		icao: "EK",
		country: "Faroe Islands",
		link: aipDenmarkLink,
		aip: "green"
	}, {
		id: "ef",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/1000px-Flag_of_Finland.svg.png",
		icao: "EF",
		country: "Finland",
		link: "https://www.ais.fi/en",
		aip: "green"
	}, {
		id: "lf",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Flag_of_France.png/1024px-Flag_of_France.png",
		icao: "LF",
		country: "France",
		link: aipFranceLink,
		aip: "green"
	}, {
		id: "fo",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Gabon.svg/1000px-Flag_of_Gabon.svg.png",
		icao: "FO",
		country: "Gabon",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "gb",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_The_Gambia.svg/1000px-Flag_of_The_Gambia.svg.png",
		icao: "GB",
		country: "Gambia",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "ug",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/1000px-Flag_of_Georgia.svg.png",
		icao: "UG",
		country: "Georgia",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "ed",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/1000px-Flag_of_Germany.svg.png",
		icao: "ED",
		country: "Germany",
		link: "https://www.eisenschmidt.aero/account/downloads",
		aip: "green"
	}, {
		id: "et",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Coat_of_arms_of_Germany.svg/1000px-Coat_of_arms_of_Germany.svg.png",
		icao: "ET",
		country: "Germany Military Airports",
		link: "https://www.milais.org/publications.php?ZnJtaWQ9MA==",
		aip: "green"
	}, {
		id: "dg",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/1000px-Flag_of_Ghana.svg.png",
		icao: "DG",
		country: "Ghana",
		link: "",
		aip: "red"
	}, {
		id: "lg",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Greece.png/1024px-Flag_of_Greece.png",
		icao: "LG",
		country: "Greece",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "bg",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_Greenland.png/1024px-Flag_of_Greenland.png",
		icao: "BG",
		country: "Greenland",
		link: aipDenmarkLink,
		aip: "green"
	}, {
		id: "mt",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Haiti.svg/1000px-Flag_of_Haiti.svg.png",
		icao: "MT",
		country: "Haiti",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "mh",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Flag_of_Honduras.svg/1000px-Flag_of_Honduras.svg.png",
		icao: "MH",
		country: "Honduras",
		link: "https://ahac.gob.hn/",
		aip: "green"
	}, {
		id: "vh",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Flag_of_Hong_Kong_%28fixed%29.svg/1000px-Flag_of_Hong_Kong_%28fixed%29.svg.png",
		icao: "VH",
		country: "Hong Kong",
		link: "https://www.ais.gov.hk/",
		aip: "green"
	}, {
		id: "lh",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/1000px-Flag_of_Hungary.svg.png",
		icao: "LH",
		country: "Hungary",
		link: "https://ais-en.hungarocontrol.hu/aip/",
		aip: "green"
	}, {
		id: "bi",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/1000px-Flag_of_Iceland.svg.png",
		icao: "BI",
		country: "Iceland",
		link: "https://eaip.isavia.is/",
		aip: "green"
	}, {
		id: "fm-eparses",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Flag_of_the_French_Southern_and_Antarctic_Lands.svg/1000px-Flag_of_the_French_Southern_and_Antarctic_Lands.svg.png",
		icao: "FM",
		country: "Illes Eparses",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "vi",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_India.png/1024px-Flag_of_India.png",
		icao: "VI",
		country: "India",
		link: "https://aim-india.aai.aero/",
		aip: "green"
	}, {
		id: "wi",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/1000px-Flag_of_Indonesia.svg.png",
		icao: "WI",
		country: "Indonesia",
		link: "https://aimindonesia.dephub.go.id/signin.php",
		aip: "green"
	}, {
		id: "oi",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/1000px-Flag_of_Iran.svg.png",
		icao: "OI",
		country: "Iran",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "or",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/1000px-Flag_of_Iraq.svg.png",
		icao: "OR",
		country: "Iraq",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "ei",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/1000px-Flag_of_Ireland.svg.png",
		icao: "EI",
		country: "Ireland",
		link: "https://www.iaa.ie/commercial-aviation/aeronautical-information-management-1",
		aip: "green"
	}, {
		id: "ll",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/1000px-Flag_of_Israel.svg.png",
		icao: "LL",
		country: "Israel",
		link: "https://www.gov.il/en/departments/guides/aip-israel?chapterIndex=1",
		aip: "green"
	}, {
		id: "li",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/1000px-Flag_of_Italy.svg.png",
		icao: "LI",
		country: "Italy",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "di",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg/1000px-Flag_of_C%C3%B4te_d%27Ivoire.svg.png",
		icao: "DI",
		country: "Ivory Coast",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "rj",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/1000px-Flag_of_Japan.svg.png",
		icao: "RJ",
		country: "Japan",
		link: "https://aisjapan.mlit.go.jp/Login.do",
		aip: "green"
	}, {
		id: "oj",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Jordan.png/1024px-Flag_of_Jordan.png",
		icao: "OJ",
		country: "Jordan",
		link: "http://www.carc.gov.jo/en/ais",
		aip: "green"
	}, {
		id: "ua",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/1000px-Flag_of_Kazakhstan.svg.png",
		icao: "UA",
		country: "Kazakhstan",
		link: "https://www.ans.kz/en/ais/eaip",
		aip: "green"
	}, {
		id: "hk",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/1000px-Flag_of_Kenya.svg.png",
		icao: "HK",
		country: "Kenia",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "rk",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/1000px-Flag_of_South_Korea.svg.png",
		icao: "RK",
		country: "South Korea",
		link: "http://ais.casa.go.kr/",
		aip: "green"
	}, {
		id: "bk",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Flag_of_Republic_of_Kosovo.svg/1000px-Flag_of_Republic_of_Kosovo.svg.png",
		icao: "BK",
		country: "Kosovo",
		link: "https://caa.rks-gov.net/en/category/aip-en/",
		aip: "green"
	}, {
		id: "ok",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/1000px-Flag_of_Kuwait.svg.png",
		icao: "OK",
		country: "Kuwait",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "uc",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/1000px-Flag_of_Kyrgyzstan.svg.png",
		icao: "UC",
		country: "Kyrgistan",
		link: "http://kan.kg/en/ais",
		aip: "green"
	}, {
		id: "fm-reunion",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Proposed_flag_of_R%C3%A9union_%28ARF%29.svg/1024px-Proposed_flag_of_R%C3%A9union_%28ARF%29.svg.png",
		icao: "FM",
		country: "La Reunion",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "ev",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/1000px-Flag_of_Latvia.svg.png",
		icao: "EV",
		country: "Latvia",
		link: "https://ais.lgs.lv/#",
		aip: "green"
	}, {
		id: "ol",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/1000px-Flag_of_Lebanon.svg.png",
		icao: "OL",
		country: "Lebanon",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "fx",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/1000px-Flag_of_Lesotho.svg.png",
		icao: "FX",
		country: "Lesotho",
		link: "",
		aip: "red"
	}, {
		id: "hl",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/1000px-Flag_of_Libya.svg.png",
		icao: "HL",
		country: "Libya",
		link: "https://caa.gov.ly/ais/aip/",
		aip: "green"
	}, {
		id: "ey",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/1000px-Flag_of_Lithuania.svg.png",
		icao: "EY",
		country: "Lithuania",
		link: "https://www.ead.eurocontrol.int/cms-eadbasic/opencms/en/login/ead-basic/",
		aip: "green"
	}, {
		id: "el",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/1000px-Flag_of_Luxembourg.svg.png",
		icao: "EL",
		country: "Luxembourg",
		link: aipBelgiumLink,
		aip: "green"
	}, {
		id: "vm",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Flag_of_Macau.svg/1000px-Flag_of_Macau.svg.png",
		icao: "VM",
		country: "Macau",
		link: "https://www.aacm.gov.mo/reference_fly.php?pageid=98&lg=eng",
		aip: "green"
	}, {
		id: "fm-madagascar",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Madagascar.svg/1000px-Flag_of_Madagascar.svg.png",
		icao: "FM",
		country: "Madagascar",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "fw",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Flag_of_Malawi.svg/1000px-Flag_of_Malawi.svg.png",
		icao: "FW",
		country: "Malawi",
		link: "",
		aip: "red"
	}, {
		id: "wm",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/1000px-Flag_of_Malaysia.svg.png",
		icao: "WM",
		country: "Malaysia",
		link: "https://aip.caam.gov.my/aip/eAIP/history-en-MS.html",
		aip: "green"
	}, {
		id: "lm",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/1000px-Flag_of_Malta.svg.png",
		icao: "LM",
		country: "Malta",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "fi",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/1000px-Flag_of_Mauritius.svg.png",
		icao: "FI",
		country: "Mauritius",
		link: "https://civil-aviation.govmu.org/Pages/ANSPUBLICATION.aspx",
		aip: "green"
	}, {
		id: "fm-mayotte",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Mayotte_%28local%29.svg/1000px-Flag_of_Mayotte_%28local%29.svg.png",
		icao: "FM",
		country: "Mayotte",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "mm",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/1000px-Flag_of_Mexico.svg.png",
		icao: "MM",
		country: "Mexico",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "lu",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/1000px-Flag_of_Moldova.svg.png",
		icao: "LU",
		country: "Moldova",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "zm",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Mongolia.svg/1000px-Flag_of_Mongolia.svg.png",
		icao: "ZM",
		country: "Mongolia",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "fq",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Mozambique.svg/1000px-Flag_of_Mozambique.svg.png",
		icao: "FQ",
		country: "Mozambique",
		link: "",
		aip: "red"
	}, {
		id: "vy",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/1000px-Flag_of_Myanmar.svg.png",
		icao: "VY",
		country: "Myanmar",
		link: "https://www.ais.gov.mm/eAIP/history-en-GB.html",
		aip: "green"
	}, {
		id: "fy",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/1000px-Flag_of_Namibia.svg.png",
		icao: "FY",
		country: "Namibia",
		link: "http://www.dca.com.na/pubs/pubs.htm",
		aip: "green"
	}, {
		id: "an",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Flag_of_Nauru.svg/1000px-Flag_of_Nauru.svg.png",
		icao: "AN",
		country: "Nauru",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "vn",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/1000px-Flag_of_Nepal.svg.png",
		icao: "VN",
		country: "Nepal",
		link: "https://e-aip.caanepal.gov.np/",
		aip: "green"
	}, {
		id: "eh",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/1000px-Flag_of_the_Netherlands.svg.png",
		icao: "EH",
		country: "Netherlands",
		link: "https://en.lvnl.nl/information-for-airmen/publications-for-airmen",
		aip: "green"
	}, {
		id: "nz",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/1000px-Flag_of_New_Zealand.svg.png",
		icao: "NZ",
		country: "New Zealand",
		link: "http://www.aip.net.nz/",
		aip: "green"
	}, {
		id: "dr",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Flag_of_Niger.svg/1000px-Flag_of_Niger.svg.png",
		icao: "DR",
		country: "Niger",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "dn",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/1000px-Flag_of_Nigeria.svg.png",
		icao: "DN",
		country: "Nigeria",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "ni",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Niue.svg/1000px-Flag_of_Niue.svg.png",
		icao: "NI",
		country: "Niue",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "as",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Norfolk_Island.svg/1000px-Flag_of_Norfolk_Island.svg.png",
		icao: "AS",
		country: "Norfolk Island",
		link: aipAustraliaLink,
		aip: "green"
	}, {
		id: "lw",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_North_Macedonia.svg/1000px-Flag_of_North_Macedonia.svg.png",
		icao: "LW",
		country: "North Macedonia",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "lc-northernCyprus",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Flag_of_the_Turkish_Republic_of_Northern_Cyprus.svg/1000px-Flag_of_the_Turkish_Republic_of_Northern_Cyprus.svg.png",
		icao: "LC",
		country: "Northern Cyprus",
		link: "http://havacilik.gov.ct.tr/en-us/-legislation/trnc-aip",
		aip: "green"
	}, {
		id: "en",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/1000px-Flag_of_Norway.svg.png",
		icao: "EN",
		country: "Norway",
		link: "https://avinor.no/en/ais/",
		aip: "green"
	}, {
		id: "oo",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/1000px-Flag_of_Oman.svg.png",
		icao: "OO",
		country: "Oman",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "op",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/1000px-Flag_of_Pakistan.svg.png",
		icao: "OP",
		country: "Pakistan",
		link: "https://www.caapakistan.com.pk/AIS/AIS_AMDT.aspx",
		aip: "green"
	}, {
		id: "mp",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/1000px-Flag_of_Panama.svg.png",
		icao: "MP",
		country: "Panama",
		link: "https://www.aeronautica.gob.pa/",
		aip: "green"
	}, {
		id: "ay",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/1000px-Flag_of_Papua_New_Guinea.svg.png",
		icao: "AY",
		country: "Papua New Guinea",
		link: "https://www.niuskypacific.com.pg/publications/",
		aip: "green"
	}, {
		id: "sg",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/1000px-Flag_of_Paraguay.svg.png",
		icao: "SG",
		country: "Paraguay",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "ep",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/1000px-Flag_of_Poland.svg.png",
		icao: "EP",
		country: "Poland",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "ot",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/1000px-Flag_of_Qatar.svg.png",
		icao: "OT",
		country: "Qatar",
		link: "https://www.caa.gov.qa/en-us/Pages/AIM.aspx",
		aip: "green"
	}, {
		id: "lr",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/1000px-Flag_of_Romania.svg.png",
		icao: "LR",
		country: "Romania",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "uu",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/1000px-Flag_of_Russia.svg.png",
		icao: "UU",
		country: "Russia",
		link: aipRussiaLink,
		aip: "green"
	}, {
		id: "hr",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/1000px-Flag_of_Rwanda.svg.png",
		icao: "HR",
		country: "Rwanda",
		link: "https://rac.co.rw/airports/aip/",
		aip: "green"
	}, {
		id: "fh-saintHelena",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Saint_Helena.svg/1000px-Flag_of_Saint_Helena.svg.png",
		icao: "FH",
		country: "Saint Helena",
		link: "",
		aip: "black"
	}, {
		id: "ns",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Samoa.svg/1000px-Flag_of_Samoa.svg.png",
		icao: "NS",
		country: "Samoa",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "fp",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Sao_Tome_and_Principe.svg/1000px-Flag_of_Sao_Tome_and_Principe.svg.png",
		icao: "FP",
		country: "Sao Tome & Principe",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "oe",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/1000px-Flag_of_Saudi_Arabia.svg.png",
		icao: "OE",
		country: "Saudi Arabia",
		link: "https://sans.com.sa/English/Pages/Login.aspx?ReturnUrl=%2fEnglish%2fAIMs%2f_layouts%2f15%2fAuthenticate.aspx%3fSource%3d%252FEnglish%252FAIMs&Source=%2FEnglish%2FAIMs",
		aip: "green"
	}, {
		id: "ly",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Flag_of_Yugoslavia_%281992%E2%80%932003%29%3B_Flag_of_Serbia_and_Montenegro_%282003%E2%80%932006%29.svg/1000px-Flag_of_Yugoslavia_%281992%E2%80%932003%29%3B_Flag_of_Serbia_and_Montenegro_%282003%E2%80%932006%29.svg.png",
		icao: "LY",
		country: "Serbia & Montenegro",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "fs",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Seychelles.svg/1000px-Flag_of_Seychelles.svg.png",
		icao: "FS",
		country: "Seychelles",
		link: "https://www.scaa.sc/index.php/service-providers/aviation-services/e-ais",
		aip: "green"
	}, {
		id: "ws",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/1000px-Flag_of_Singapore.svg.png",
		icao: "WS",
		country: "Singapore",
		link: "https://aim-sg.caas.gov.sg/eaip.html",
		aip: "green"
	}, {
		id: "lz",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/1000px-Flag_of_Slovakia.svg.png",
		icao: "LZ",
		country: "Slovakia",
		link: "https://aim.lps.sk/web/",
		aip: "green"
	}, {
		id: "lj",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/1000px-Flag_of_Slovenia.svg.png",
		icao: "LJ",
		country: "Slovenia",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "ag",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Solomon_Islands.svg/1000px-Flag_of_the_Solomon_Islands.svg.png",
		icao: "AG",
		country: "Solomon Islands",
		link: "",
		aip: "black"
	}, {
		id: "hc",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Somalia.svg/1000px-Flag_of_Somalia.svg.png",
		icao: "HC",
		country: "Somalia",
		link: "http://aip.scaa.gov.so/",
		aip: "green"
	}, {
		id: "fa",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/1000px-Flag_of_South_Africa.svg.png",
		icao: "FA",
		country: "South Africa",
		link: "",
		aip: "red"
	}, {
		id: "le",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/1000px-Flag_of_Spain.svg.png",
		icao: "LE",
		country: "Spain",
		link: "https://aip.enaire.es/AIP/AIP-en.html",
		aip: "green"
	}, {
		id: "vc",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/1000px-Flag_of_Sri_Lanka.svg.png",
		icao: "VC",
		country: "Sri Lanka",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "es",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Sweden.svg/1000px-Flag_of_Sweden.svg.png",
		icao: "ES",
		country: "Sweden",
		link: "https://aro.lfv.se/Editorial/View/IAIP",
		aip: "green"
	}, {
		id: "rc",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/1000px-Flag_of_the_Republic_of_China.svg.png",
		icao: "RC",
		country: "Taiwan",
		link: "http://eaip.caa.gov.tw/eaip/home.faces",
		aip: "green"
	}, {
		id: "ut-tajikistan",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/1000px-Flag_of_Tajikistan.svg.png",
		icao: "UT",
		country: "Tajikistan",
		link: "http://www.caica.ru/aiptjk/validaip/index.htm",
		aip: "green"
	}, {
		id: "ft",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Chad.svg/1000px-Flag_of_Chad.svg.png",
		icao: "FT",
		country: "Chad",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "vt",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/1000px-Flag_of_Thailand.svg.png",
		icao: "VT",
		country: "Thailand",
		link: "https://aip.caat.or.th/",
		aip: "green"
	}, {
		id: "wp",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_East_Timor.svg/1000px-Flag_of_East_Timor.svg.png",
		icao: "WP",
		country: "Timor Leste",
		link: "",
		aip: "black"
	}, {
		id: "dx",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Flag_of_Togo.svg/1000px-Flag_of_Togo.svg.png",
		icao: "DX",
		country: "Togo",
		link: asecnaLink,
		aip: "green"
	}, {
		id: "nf-tonga",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Tonga.svg/1000px-Flag_of_Tonga.svg.png",
		icao: "NF",
		country: "Tonga",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "fh-tristan",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Tristan_da_Cunha.svg/1000px-Flag_of_Tristan_da_Cunha.svg.png",
		icao: "FH",
		country: "Tristan da Cunha",
		link: "",
		aip: "black"
	}, {
		id: "dt",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/1000px-Flag_of_Tunisia.svg.png",
		icao: "DT",
		country: "Tunisia",
		link: "http://www.oaca.nat.tn/index.php?id=750&L=2",
		aip: "green"
	}, {
		id: "lt",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/1000px-Flag_of_Turkey.svg.png",
		icao: "LT",
		country: "Turkey",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "ut-turkmenistan",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Turkmenistan.svg/1000px-Flag_of_Turkmenistan.svg.png",
		icao: "UT",
		country: "Turkmenistan",
		link: aipRussiaLink,
		aip: "green"
	}, {
		id: "ng",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tuvalu.svg/1000px-Flag_of_Tuvalu.svg.png",
		icao: "NG",
		country: "Tuvalu",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "hu",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/1000px-Flag_of_Uganda.svg.png",
		icao: "HU",
		country: "Uganda",
		link: "https://aim.caa.co.ug/eAIP",
		aip: "green"
	}, {
		id: "uk",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/1000px-Flag_of_Ukraine.svg.png",
		icao: "UK",
		country: "Ukraine",
		link: "http://www.aisukraine.net/titul_en.php",
		aip: "green"
	}, {
		id: "om",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/1000px-Flag_of_the_United_Arab_Emirates.svg.png",
		icao: "OM",
		country: "United Arab Emirates",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "eg",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Flag_of_the_United_Kingdom.svg/1000px-Flag_of_the_United_Kingdom.svg.png",
		icao: "EG",
		country: "United Kingdom",
		link: "http://www.nats-uk.ead-it.com/public/index.php.html",
		aip: "green"
	}, {
		id: "kd",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_the_U.S..svg/1000px-Flag_of_the_U.S..svg.png",
		icao: "KD",
		country: "United States of America",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "su",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/1000px-Flag_of_Uruguay.svg.png",
		icao: "SU",
		country: "Uruguay",
		link: "https://www.dinacia.gub.uy/ais/aip-uruguay/english",
		aip: "green"
	}, {
		id: "ut-uzbekistan",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/1000px-Flag_of_Uzbekistan.svg.png",
		icao: "UT",
		country: "Uzbekistan",
		link: aipRussiaLink,
		aip: "green"
	}, {
		id: "nv",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Vanuatu.svg/1000px-Flag_of_Vanuatu.svg.png",
		icao: "NV",
		country: "Vanuatu",
		link: toolboxeaipLink,
		aip: "yellow"
	}, {
		id: "sv",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Venezuela.svg/1000px-Flag_of_Venezuela.svg.png",
		icao: "SV",
		country: "Venezuela",
		link: "http://www.inac.gob.ve/eaip/history-en-GB.html",
		aip: "green"
	}, {
		id: "vv",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/1000px-Flag_of_Vietnam.svg.png",
		icao: "VV",
		country: "Vietnam",
		link: "https://vnaic.vn/index.php?option=com_content&view=category&id=53%3Aaip&layout=blog&Itemid=92&lang=en",
		aip: "green"
	}, {
		id: "fl",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/1000px-Flag_of_Zambia.svg.png",
		icao: "FL",
		country: "Zambia",
		link: "",
		aip: "red"
	}, {
		id: "fv",
		img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/1000px-Flag_of_Zimbabwe.svg.png",
		icao: "FV",
		country: "Zimbabwe",
		link: "",
        aip: "red"
	}

];
