image: atlassian/default-image:2

pipelines:
  default:
   - step:
        name: Deploy to S3
        deployment: production
        script:
          - pipe: atlassian/aws-s3-deploy:0.3.8
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'eu-central-1'
              S3_BUCKET: 'toolboxv2'
              LOCAL_PATH: ''
              ACL: 'public-read'