const locisFIR = [
"BGGL", "BGXX", 
			"BIRD", "BIXX", 
			"CYHQ", 
			"CZEG", "CZQM", "CZQX", "CZUL", "CZVR", "CZWG", "CZXX", "CZYZ",
			"DAAA", "DAXX",
			"DBXX", 
			"DFXX", 
			"DGAC", "DGXX", 
			"DIXX", 
			"DNKK", "DNXX", 
			"DRRR", "DRXX", 
			"DTTC", "DTXX", 
			"DXXX", 
			"EBBU", "EBXX", 
			"EDGG", "EDMM", "EDWW", "EDXX", 
			"EETT", "EEXX", 
			"EFIN", "EFXX",
			"EGGX", "EGPX", "EGTT", "EGXX", 
			"EHAA", "EHXX", 
			"EISN", "EIXX", 
			"EKDK", "EKXX",
			"ELXX", 
			"ENOB", "ENOR", "ENXX", 
			"EPWW", "EPXX", 
			"ESAA", "ESXX", 
			"EVRR", "EVXX",
			"EYVL", "EYXX", 
			"FACA", "FAJA", "FAJN", "FAJO", "FAXX", 
			"FBGR", "FBXX", 
			"FCCC", "FCXX", 
			"FEXX",
			"FGXX", 
			"FIMM", "FIXX", 
			"FKXX", 
			"FLFI", "FLXX", 
			"FMMM", "FMXX", 
			"FNAN", "FNXX",
			"FOXX", 
			"FPXX", 
			"FQBE", "FQXX", 
			"FSSS", "FSXX", 
			"FTTT", "FTXX", 
			"FVHF", "FVXX",
			"FWLL", "FWXX", 
			"FYWH", "FYXX", 
			"FZXX", "FZZA", 
			"GAXX", 
			"GBXX", 
			"GCCC", "GCXX", 
			"GFXX", 
			"GGXX", 
			"GLRB", "GLXX", 
			"GMMM", "GMXX",
			"GOOO", "GOXX", 
			"GQXX", 
			"GUXX", 
			"GVSC", "GVXX", 
			"HAAA", "HAXX", 
			"HBBA", "HBXX", 
			"HCSM", "HCXX", 
			"HDXX", 
			"HECC", "HEXX", 
			"HHAA", "HHXX", 
			"HKNA", "HKXX", 
			"HLLL", "HLXX", 
			"HRXX", "HRYR", 
			"HSSS", "HSXX", 
			"HTDC", "HTXX", 
			"HUEC", "HUXX",
			"KFDC", 
			"KZAB", "KZAK", "KZAU", "KZBW", "KZDC", "KZDV", "KZFW", "KZHU", "KZID", "KZJX", 
			"KZKC", "KZLA", "KZLC", "KZMA", "KZME", "KZMP", "KZNY", "KZOA", "KZOB", "KZSE", 
			"KZTL", "KZWY", "KZXX",
			"LAAA", "LAXX", 
			"LBSR", "LBXX", 
			"LCCC", "LCXX", 
			"LDXX", "LDZO", 
			"LECB", "LECM", "LEXX", 
			"LFBB", "LFEE", "LFFF", "LFMM", "LFRR", "LFXX", 
			"LGGG", "LGXX", 
			"LHCC", "LHXX", 
			"LIBB", "LIMM", "LIRR", "LIXX", 
			"LJLA", "LJXX", 
			"LKAA", "LKXX", 
			"LLLL", "LLXX", 
			"LMMM", "LMXX", 
			"LNXX", 
			"LOVV", "LOXX", 
			"LPPC", "LPPO", "LPXX", 
			"LQSB", "LQXX", 
			"LRBB", "LRXX", 
			"LSAS", 
			"LTAA", "LTBB", "LTXX", 
			"LUUU", "LUXX", 
			"LWSS", "LWXX", 
			"LXXX", 
			"LYBA", "LYXX", 
			"LZBB", "LZXX",
			"MDCS", "MDXX", 
			"MGXX", 
			"MHTG", "MHXX", 
			"MKJK", "MKXX", 
			"MMFR", "MMID", "MMXX",
			"MNXX", 
			"MTEG", "MTXX", 
			"MUFH", "MUXX", 
			"MYNA", "MYXX",
			"OAKX", "OAXX", 
			"OBBB", "OBXX", 
			"OEJD", "OEXX", 
			"OIIX", "OIXX", 
			"OJAC", "OJXX",
			"OKAC", "OKXX", 
			"OLBB", "OLXX", 
			"OMAE", "OMXX", 
			"OOMM", "OOXX", 
			"OPKR", "OPLR", "OPXX", 
			"ORBB", "ORXX", 
			"OSTT", "OSXX", 
			"OTXX", 
			"OYSC", "OYXX", 
			"PAZA",
			"RCAA", "RCXX", 
			"RJCG", "RJDG", "RJJJ", "RJTG", "RJXX", 
			"RKRR", "RKXX", 
			"RORG",
			"RPHI", "RPXX",
			"SBAO", "SBAZ", "SBBS", "SBCW", "SBRE", "SBWB", "SBWF", "SBWH", "SBWJ", "SBWZ",
			"SBXB", "SBXP", "SBXR", "SBXS", "SBXT", "SBXX", 
			"TJZS", 
			"TNCF", "TNXX", 
			"TTXX", "TTZP", 
			"TXKF", "TXXX", 
			"UAAA", "UACC", "UAII", "UAKD", "UARR", "UASS", "UATA", "UATE", "UATG", "UATT",
			"UAXX", 
			"UBBA", "UBXX", 
			"UCFM", "UCFO", "UCXX",
			"UDDD", "UDXX", 
			"UEEE", "UELL", "UEMO", "UERP", "UERR", 
			"UGGG", "UGXX", 
			"UHHH", "UHMM", "UHPP", 
			"UIII", 
			"UKBV", "UKDV", "UKFV", "UKLV", "UKOV", "UKXX", 
			"ULAA", "ULAM", "ULKK", "ULLL","ULMM", "ULWW", 
			"UMKK", "UMMV", "UMXX", 
			"UNKL", "UNNT", 
			"URFV", "URRV", 
			"USCC", "USCM", "USDD", "USDK", "USDS", "USKK", "USPP", "USSS", "USTR", 
			"UTAA", "UTAK", "UTAT", "UTAV", "UTDD", "UTNR", "UTSD", "UTTR", "UTXX", 
			"UUWV", "UUXX", "UUYY", "UWKD",
			"UWWW", 
			"UXXX", 
			"VABF", "VAXX", 
			"VCCF", "VCXX", 
			"VDPP", "VDXX", 
			"VECF", "VEXX", 
			"VGFR", "VGXX",
			"VHHK", "VHXX",
			"VIDF", "VIXX", 
			"VLVT", "VLXX", 
			"VNSM", "VNXX", 
			"VOMF", "VOXX",
			"VRMF", "VRXX", 
			"VTBB", "VTXX", 
			"VVTS", "VVVV", "VVXX", 
			"VYXX", "VYYF",
			"WAAF", "WAXX", 
			"WIIF", "WIXX", 
			"WMFC", "WMXX", 
			"WSJC", "WSXX", 
			"ZBPE", 
			"ZGZU", 
			"ZHWH", 
			"ZJSA", 
			"ZKKP", 
			"ZLHW", 
			"ZMUB", 
			"ZPKM", 
			"ZSHA", 
			"ZWUQ",
			"ZXXX", 
			"ZYSH"
]
